/**
 * What happens to a synced ticket when its run ends.
 *
 * Called once from the gateway's terminal handler, fail-soft, the way
 * `finalizeCreatedTicket` is: a connector that cannot post must not be able to
 * fail a run's terminal update. The run happened either way, and the
 * transcript is the record.
 *
 * Two artefacts come out of a terminal run on a synced ticket:
 *
 * - a work note, queued durably, so the customer's technician sees what Axel
 *   found in the system they actually work in;
 * - a proposal row, when the environment was in shadow, so the suppressed
 *   intent can be reviewed and compared against what the human did.
 *
 * Neither is generated by the agent. The proposal *is* the transcript, which
 * is why the shadow guard suppresses at the tool layer rather than asking the
 * model to describe what it would have done.
 */

import { and, asc, eq, isNull, like } from "drizzle-orm";
import { db } from "@/db";
import {
	agentRuns,
	agentSteps,
	itsmConnectors,
	itsmProposals,
	itsmTicketOrigins,
} from "@/db/schema";
import { loadRunEnvironment } from "../environments/runtime";
import { renderWorkNote } from "./core";
import { queueWorkNote } from "./writeback";

/**
 * The refusals the shadow guard produced during this run.
 *
 * `assertEnvironmentAllowed` throws before any cluster or device call, and the
 * gateway records the refusal as a step, so the intent survives in the
 * transcript without the agent ever being told the environment was in shadow.
 * Reading those steps back is what turns a suppression into a proposal.
 */
export async function suppressedCallsForRun(runId: string) {
	const rows = await db
		.select({
			toolName: agentSteps.toolName,
			toolInput: agentSteps.toolInput,
			ordinal: agentSteps.ordinal,
		})
		.from(agentSteps)
		.where(
			and(
				eq(agentSteps.runId, runId),
				like(agentSteps.error, "%shadow mode; refusing write tool%"),
			),
		)
		.orderBy(asc(agentSteps.ordinal));
	return rows.map((row) => ({
		tool: row.toolName ?? "unknown",
		input: row.toolInput,
		ordinal: row.ordinal,
	}));
}

export type TerminalRun = {
	runId: string;
	status: string;
	outcome: string | null;
	evidence: string | null;
	resolutionCode: string | null;
};

/**
 * Queues the write-back and records the proposal. Safe to call for any run;
 * returns immediately when the ticket did not come from a connector.
 */
export async function onRunTerminal(run: TerminalRun): Promise<void> {
	// The ticket is resolved here rather than passed in, because the gateway's
	// terminal handler holds it only inside its transaction.
	const [linked] = await db
		.select({ ticketId: agentRuns.ticketId })
		.from(agentRuns)
		.where(eq(agentRuns.id, run.runId))
		.limit(1);
	if (!linked) return;
	const ticketId = linked.ticketId;

	const [origin] = await db
		.select({
			connectorId: itsmTicketOrigins.connectorId,
			externalId: itsmTicketOrigins.externalId,
			externalKey: itsmTicketOrigins.externalKey,
			connectorEnabled: itsmConnectors.enabled,
		})
		.from(itsmTicketOrigins)
		.innerJoin(
			itsmConnectors,
			eq(itsmConnectors.id, itsmTicketOrigins.connectorId),
		)
		.where(eq(itsmTicketOrigins.ticketId, ticketId))
		.limit(1);
	if (!origin) return;

	// Resolved rather than passed in, so the gateway's terminal handler does not
	// have to carry an extra field and cannot disagree with the guard that
	// actually did the suppressing.
	const shadow =
		(await loadRunEnvironment(run.runId)).environment?.mode === "shadow";
	const suppressed = await suppressedCallsForRun(run.runId);

	if (shadow)
		await db
			.insert(itsmProposals)
			.values({
				id: crypto.randomUUID(),
				runId: run.runId,
				ticketId,
				connectorId: origin.connectorId,
				suppressedCalls: suppressed,
				postedAt: new Date(),
			})
			// One proposal per run; a replayed terminal update must not create a
			// second, which would double-count the run in every agreement figure.
			.onConflictDoNothing({ target: itsmProposals.runId });

	// A disabled connector still gets its proposal recorded — the evaluation
	// data is ours — but nothing is queued for a connection that cannot deliver.
	if (!origin.connectorEnabled) return;

	await queueWorkNote({
		connectorId: origin.connectorId,
		ticketId,
		runId: run.runId,
		externalId: origin.externalId,
		correlationId: origin.externalKey,
		note: renderWorkNote({
			shadow,
			status: run.status,
			outcome: run.outcome,
			evidence: run.evidence,
			resolutionCode: run.resolutionCode,
			suppressedCalls: suppressed,
			runUrl: null,
		}),
	});
}

/**
 * Fills in what the human actually did, once the foreign ticket has moved on.
 *
 * A proposal is only half an evaluation sample until this runs: without it the
 * agreement surface compares against null and every row reads as the same
 * action class. It is a second read path with its own cadence rather than part
 * of the main poll, because it revisits records the watermark has already
 * passed — the watermark answers "what changed", and this asks "what became of
 * the ones we proposed on".
 *
 * Deliberately re-reads only proposals with no outcome yet, oldest first, in
 * small batches. A ticket the customer never closes is never scored, which is
 * correct: there is nothing to compare against.
 */
export async function backfillProposalOutcomes(
	fetchState: (
		connectorId: string,
		externalId: string,
	) => Promise<{ resolution: string | null; closedBy: string | null } | null>,
	limit = 25,
): Promise<number> {
	const pending = await db
		.select({
			id: itsmProposals.id,
			connectorId: itsmProposals.connectorId,
			externalId: itsmTicketOrigins.externalId,
		})
		.from(itsmProposals)
		.innerJoin(
			itsmTicketOrigins,
			eq(itsmTicketOrigins.ticketId, itsmProposals.ticketId),
		)
		.where(isNull(itsmProposals.foreignResolution))
		.orderBy(asc(itsmProposals.createdAt))
		.limit(Math.min(Math.max(limit, 1), 100));

	let filled = 0;
	for (const row of pending) {
		const state = await fetchState(row.connectorId, row.externalId);
		// A ticket still open has no outcome yet. Recording "unknown" would put a
		// value into the agreement figures that is not an observation.
		if (!state?.resolution) continue;
		await db
			.update(itsmProposals)
			.set({
				foreignResolution: state.resolution,
				foreignClosedBy: state.closedBy,
				observedAt: new Date(),
			})
			.where(eq(itsmProposals.id, row.id));
		filled += 1;
	}
	return filled;
}
