import type { RouterClient } from "@orpc/server";
import { agentRunsRouter } from "./agent-runs";
import { assetsRouter } from "./assets";
import { automationRouter } from "./automation";
import { catalogueRouter } from "./catalogue";
import { changesRouter } from "./changes";
import { cmdbRouter } from "./cmdb";
import { connectorsRouter } from "./connectors";
import { deviceProposalsRouter } from "./device-proposals";
import { devicesRouter } from "./devices";
import { documentsRouter } from "./documents";
import { environmentsRouter } from "./environments";
import { identityRouter } from "./identity";
import { intakeRouter } from "./intake";
import { knowledgeRouter } from "./knowledge";
import { mailRouter } from "./mail";
import { problemsRouter } from "./problems";
import { schedulingRouter } from "./scheduling";
import { sharedRouter } from "./shared";
import { statusRouter } from "./status";
import { suppliersRouter } from "./suppliers";
import { ticketsRouter } from "./tickets";

export const appRouter = {
	listForms: catalogueRouter.listForms,
	createForm: catalogueRouter.createForm,
	updateForm: catalogueRouter.updateForm,
	publishForm: catalogueRouter.publishForm,
	setSubcategoryForm: catalogueRouter.setSubcategoryForm,
	listCatalogue: catalogueRouter.listCatalogue,
	listProblems: problemsRouter.listProblems,
	getProblem: problemsRouter.getProblem,
	createProblem: problemsRouter.createProblem,
	updateProblem: problemsRouter.updateProblem,
	linkProblemTickets: problemsRouter.linkProblemTickets,
	closeProblem: problemsRouter.closeProblem,
	getTicketServiceRecords: ticketsRouter.getTicketServiceRecords,
	listChanges: changesRouter.listChanges,
	getChange: changesRouter.getChange,
	createChange: changesRouter.createChange,
	updateChange: changesRouter.updateChange,
	voteOnChange: changesRouter.voteOnChange,
	listKnowledgeArticles: knowledgeRouter.listKnowledgeArticles,
	getKnowledgeArticle: knowledgeRouter.getKnowledgeArticle,
	createKnowledgeArticle: knowledgeRouter.createKnowledgeArticle,
	updateKnowledgeArticle: knowledgeRouter.updateKnowledgeArticle,
	listPublicKnowledge: knowledgeRouter.listPublicKnowledge,
	getPublicKnowledgeArticle: knowledgeRouter.getPublicKnowledgeArticle,
	listRequestCatalogue: catalogueRouter.listRequestCatalogue,
	createCatalogueRequest: catalogueRouter.createCatalogueRequest,
	listDeviceProposals: deviceProposalsRouter.listDeviceProposals,
	decideDeviceProposal: deviceProposalsRouter.decideDeviceProposal,
	listApprovals: catalogueRouter.listApprovals,
	decideApproval: catalogueRouter.decideApproval,
	getMyApprovalStatus: catalogueRouter.getMyApprovalStatus,
	listCmdbClasses: cmdbRouter.listCmdbClasses,
	createCmdbClass: cmdbRouter.createCmdbClass,
	updateCmdbClass: cmdbRouter.updateCmdbClass,
	deleteCmdbClass: cmdbRouter.deleteCmdbClass,
	listCmdbObjects: cmdbRouter.listCmdbObjects,
	cmdbImpact: cmdbRouter.cmdbImpact,
	listTicketCmdbObjects: cmdbRouter.listTicketCmdbObjects,
	linkTicketCmdbObject: cmdbRouter.linkTicketCmdbObject,
	unlinkTicketCmdbObject: cmdbRouter.unlinkTicketCmdbObject,
	listFieldDefinitions: automationRouter.listFieldDefinitions,
	listTicketFieldDefinitions: automationRouter.listTicketFieldDefinitions,
	createFieldDefinition: automationRouter.createFieldDefinition,
	setFieldDefinitionActive: automationRouter.setFieldDefinitionActive,
	listTicketRules: automationRouter.listTicketRules,
	createTicketRule: automationRouter.createTicketRule,
	updateTicketRule: automationRouter.updateTicketRule,
	deleteTicketRule: automationRouter.deleteTicketRule,
	listWorkflows: automationRouter.listWorkflows,
	createWorkflow: automationRouter.createWorkflow,
	updateWorkflow: automationRouter.updateWorkflow,
	deleteWorkflow: automationRouter.deleteWorkflow,
	listWebhookDeliveries: automationRouter.listWebhookDeliveries,
	retryWebhookDeliveries: automationRouter.retryWebhookDeliveries,
	listNotifications: automationRouter.listNotifications,
	markNotificationRead: automationRouter.markNotificationRead,
	listSavedViews: automationRouter.listSavedViews,
	createSavedView: automationRouter.createSavedView,
	updateSavedView: automationRouter.updateSavedView,
	deleteSavedView: automationRouter.deleteSavedView,
	reconcileSearch: automationRouter.reconcileSearch,
	listApiKeys: automationRouter.listApiKeys,
	createApiKey: automationRouter.createApiKey,
	updateApiKey: automationRouter.updateApiKey,
	revokeApiKey: automationRouter.revokeApiKey,
	search: automationRouter.search,
	readStatus: statusRouter.readStatus,
	upsertStatusService: statusRouter.upsertStatusService,
	upsertImpactLevel: statusRouter.upsertImpactLevel,
	createStatusIncident: statusRouter.createStatusIncident,
	updateStatusIncident: statusRouter.updateStatusIncident,
	readDeviceInventory: assetsRouter.readDeviceInventory,
	listAssets: assetsRouter.listAssets,
	previewAssetImport: assetsRouter.previewAssetImport,
	importAssets: assetsRouter.importAssets,
	listAssetImportRuns: assetsRouter.listAssetImportRuns,
	listAssetImportRejections: assetsRouter.listAssetImportRejections,
	listAssetHistory: assetsRouter.listAssetHistory,
	setAssetDynamicFields: assetsRouter.setAssetDynamicFields,
	listTicketOrigins: mailRouter.listTicketOrigins,
	listMailboxes: mailRouter.listMailboxes,
	upsertMailbox: mailRouter.upsertMailbox,
	deleteMailbox: mailRouter.deleteMailbox,
	listMailboxActivity: mailRouter.listMailboxActivity,
	ingestChannelMessage: mailRouter.ingestChannelMessage,
	checkoutAsset: assetsRouter.checkoutAsset,
	checkinAsset: assetsRouter.checkinAsset,
	listSoftwareEntitlements: assetsRouter.listSoftwareEntitlements,
	createSoftwareEntitlement: assetsRouter.createSoftwareEntitlement,
	allocateSoftwareLicence: assetsRouter.allocateSoftwareLicence,
	revokeSoftwareAllocation: assetsRouter.revokeSoftwareAllocation,
	readSoftwareCompliance: assetsRouter.readSoftwareCompliance,
	setTicketSchedule: schedulingRouter.setTicketSchedule,
	snoozeTicket: schedulingRouter.snoozeTicket,
	listCalendar: schedulingRouter.listCalendar,
	listRecurrences: schedulingRouter.listRecurrences,
	createRecurrence: schedulingRouter.createRecurrence,
	updateRecurrence: schedulingRouter.updateRecurrence,
	deleteRecurrence: schedulingRouter.deleteRecurrence,
	triggerRecurrences: schedulingRouter.triggerRecurrences,
	getDashboardArrangement: automationRouter.getDashboardArrangement,
	setDashboardArrangement: automationRouter.setDashboardArrangement,
	listAuthProviders: identityRouter.listAuthProviders,
	listEmailTemplates: mailRouter.listEmailTemplates,
	createEmailTemplate: mailRouter.createEmailTemplate,
	updateEmailTemplate: mailRouter.updateEmailTemplate,
	deleteEmailTemplate: mailRouter.deleteEmailTemplate,
	listEmailTemplateRules: mailRouter.listEmailTemplateRules,
	setEmailTemplateRule: mailRouter.setEmailTemplateRule,
	deleteEmailTemplateRule: mailRouter.deleteEmailTemplateRule,
	previewDirectorySync: identityRouter.previewDirectorySync,
	applyDirectorySync: identityRouter.applyDirectorySync,
	listDocuments: documentsRouter.listDocuments,
	createLinkDocument: documentsRouter.createLinkDocument,
	unlinkDocument: documentsRouter.unlinkDocument,
	startIntakeDraft: intakeRouter.startIntakeDraft,
	sendIntakeMessage: intakeRouter.sendIntakeMessage,
	getIntakeDraft: intakeRouter.getIntakeDraft,
	patchIntakeDraft: intakeRouter.patchIntakeDraft,
	submitIntakeDraft: intakeRouter.submitIntakeDraft,
	discardIntakeDraft: intakeRouter.discardIntakeDraft,
	intakeCapabilities: intakeRouter.intakeCapabilities,
	listSuppliers: suppliersRouter.listSuppliers,
	listContracts: suppliersRouter.listContracts,
	listEnvironments: environmentsRouter.listEnvironments,
	createEnvironment: environmentsRouter.createEnvironment,
	updateEnvironment: environmentsRouter.updateEnvironment,
	deleteEnvironment: environmentsRouter.deleteEnvironment,
	linkTicketEnvironment: environmentsRouter.linkTicketEnvironment,
	unlinkTicketEnvironment: environmentsRouter.unlinkTicketEnvironment,
	listEmailSendLog: mailRouter.listEmailSendLog,
	healthCheck: sharedRouter.healthCheck,
	privateData: identityRouter.privateData,
	createTicket: ticketsRouter.createTicket,
	listTickets: ticketsRouter.listTickets,
	getMyTicket: ticketsRouter.getMyTicket,
	heartbeatTicketPresence: ticketsRouter.heartbeatTicketPresence,
	listTicketPresence: ticketsRouter.listTicketPresence,
	listTicketSla: ticketsRouter.listTicketSla,
	submitTicketCsat: ticketsRouter.submitTicketCsat,
	getTicket: ticketsRouter.getTicket,
	addTicketMessage: ticketsRouter.addTicketMessage,
	addMyTicketMessage: ticketsRouter.addMyTicketMessage,
	getRun: agentRunsRouter.getRun,
	startRun: agentRunsRouter.startRun,
	cancelRun: agentRunsRouter.cancelRun,
	listTicketLinks: ticketsRouter.listTicketLinks,
	linkTickets: ticketsRouter.linkTickets,
	unlinkTickets: ticketsRouter.unlinkTickets,
	mergeTickets: ticketsRouter.mergeTickets,
	unmergeTicket: ticketsRouter.unmergeTicket,
	listTicketAudit: ticketsRouter.listTicketAudit,
	listTicketRuleFirings: ticketsRouter.listTicketRuleFirings,
	listTicketTimeEntries: ticketsRouter.listTicketTimeEntries,
	addTicketTimeEntry: ticketsRouter.addTicketTimeEntry,
	lookupTicket: ticketsRouter.lookupTicket,
	listTicketAssignmentOptions: ticketsRouter.listTicketAssignmentOptions,
	listPendingReasons: ticketsRouter.listPendingReasons,
	setTicketDynamicFields: ticketsRouter.setTicketDynamicFields,
	updateTicket: ticketsRouter.updateTicket,
	listMyDevices: devicesRouter.listMyDevices,
	createDeviceEnrolmentToken: devicesRouter.createDeviceEnrolmentToken,
	rotateDeviceCredential: devicesRouter.rotateDeviceCredential,
	revokeDevice: devicesRouter.revokeDevice,
	listDevices: devicesRouter.listDevices,
	listDeviceCommands: devicesRouter.listDeviceCommands,
	ticketStats: ticketsRouter.ticketStats,
	listCapabilities: identityRouter.listCapabilities,
	listPeople: identityRouter.listPeople,
	setUserKind: identityRouter.setUserKind,
	listRoles: identityRouter.listRoles,
	getRole: identityRouter.getRole,
	updateRoleCapabilities: identityRouter.updateRoleCapabilities,
	assignRole: identityRouter.assignRole,
	listDepartments: identityRouter.listDepartments,
	createDepartment: identityRouter.createDepartment,
	listTeams: identityRouter.listTeams,
	createTeam: identityRouter.createTeam,
	updateTeam: identityRouter.updateTeam,

	...connectorsRouter,
};

export type AppRouter = typeof appRouter;
export type AppRouterClient = RouterClient<typeof appRouter>;
