// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.35.1
// source: axioma.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunUpdate_Kind int32

const (
	RunUpdate_KIND_UNSPECIFIED RunUpdate_Kind = 0
	RunUpdate_KIND_THINK       RunUpdate_Kind = 1
	RunUpdate_KIND_TOOL_CALL   RunUpdate_Kind = 2
	RunUpdate_KIND_OBSERVATION RunUpdate_Kind = 3
	RunUpdate_KIND_DECISION    RunUpdate_Kind = 4
	RunUpdate_KIND_TERMINAL    RunUpdate_Kind = 5
)

// Enum value maps for RunUpdate_Kind.
var (
	RunUpdate_Kind_name = map[int32]string{
		0: "KIND_UNSPECIFIED",
		1: "KIND_THINK",
		2: "KIND_TOOL_CALL",
		3: "KIND_OBSERVATION",
		4: "KIND_DECISION",
		5: "KIND_TERMINAL",
	}
	RunUpdate_Kind_value = map[string]int32{
		"KIND_UNSPECIFIED": 0,
		"KIND_THINK":       1,
		"KIND_TOOL_CALL":   2,
		"KIND_OBSERVATION": 3,
		"KIND_DECISION":    4,
		"KIND_TERMINAL":    5,
	}
)

func (x RunUpdate_Kind) Enum() *RunUpdate_Kind {
	p := new(RunUpdate_Kind)
	*p = x
	return p
}

func (x RunUpdate_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RunUpdate_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_axioma_proto_enumTypes[0].Descriptor()
}

func (RunUpdate_Kind) Type() protoreflect.EnumType {
	return &file_axioma_proto_enumTypes[0]
}

func (x RunUpdate_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RunUpdate_Kind.Descriptor instead.
func (RunUpdate_Kind) EnumDescriptor() ([]byte, []int) {
	return file_axioma_proto_rawDescGZIP(), []int{5, 0}
}

type AgentMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentMessage_Hello
	//	*AgentMessage_RunUpdate
	//	*AgentMessage_ToolRequest
	//	*AgentMessage_Heartbeat
	Payload       isAgentMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_axioma_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_axioma_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_axioma_proto_rawDescGZIP(), []int{0}
}

func (x *AgentMessage) GetPayload() isAgentMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentMessage) GetHello() *AgentHello {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *AgentMessage) GetRunUpdate() *RunUpdate {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_RunUpdate); ok {
			return x.RunUpdate
		}
	}
	return nil
}

func (x *AgentMessage) GetToolRequest() *ToolRequest {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_ToolRequest); ok {
			return x.ToolRequest
		}
	}
	return nil
}

func (x *AgentMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isAgentMessage_Payload interface {
	isAgentMessage_Payload()
}

type AgentMessage_Hello struct {
	Hello *AgentHello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type AgentMessage_RunUpdate struct {
	RunUpdate *RunUpdate `protobuf:"bytes,2,opt,name=run_update,json=runUpdate,proto3,oneof"`
}

type AgentMessage_ToolRequest struct {
	ToolRequest *ToolRequest `protobuf:"bytes,3,opt,name=tool_request,json=toolRequest,proto3,oneof"`
}

type AgentMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,4,opt,name=heartbeat,proto3,oneof"`
}

func (*AgentMessage_Hello) isAgentMessage_Payload() {}

func (*AgentMessage_RunUpdate) isAgentMessage_Payload() {}

func (*AgentMessage_ToolRequest) isAgentMessage_Payload() {}

func (*AgentMessage_Heartbeat) isAgentMessage_Payload() {}

type ApiMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ApiMessage_StartRun
	//	*ApiMessage_ToolResult
	//	*ApiMessage_CancelRun
	//	*ApiMessage_Heartbeat
	Payload       isApiMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiMessage) Reset() {
	*x = ApiMessage{}
	mi := &file_axioma_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiMessage) ProtoMessage() {}

func (x *ApiMessage) ProtoReflect() protoreflect.Message {
	mi := &file_axioma_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiMessage.ProtoReflect.Descriptor instead.
func (*ApiMessage) Descriptor() ([]byte, []int) {
	return file_axioma_proto_rawDescGZIP(), []int{1}
}

func (x *ApiMessage) GetPayload() isApiMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ApiMessage) GetStartRun() *StartRun {
	if x != nil {
		if x, ok := x.Payload.(*ApiMessage_StartRun); ok {
			return x.StartRun
		}
	}
	return nil
}

func (x *ApiMessage) GetToolResult() *ToolResult {
	if x != nil {
		if x, ok := x.Payload.(*ApiMessage_ToolResult); ok {
			return x.ToolResult
		}
	}
	return nil
}

func (x *ApiMessage) GetCancelRun() *CancelRun {
	if x != nil {
		if x, ok := x.Payload.(*ApiMessage_CancelRun); ok {
			return x.CancelRun
		}
	}
	return nil
}

func (x *ApiMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*ApiMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isApiMessage_Payload interface {
	isApiMessage_Payload()
}

type ApiMessage_StartRun struct {
	StartRun *StartRun `protobuf:"bytes,1,opt,name=start_run,json=startRun,proto3,oneof"`
}

type ApiMessage_ToolResult struct {
	ToolResult *ToolResult `protobuf:"bytes,2,opt,name=tool_result,json=toolResult,proto3,oneof"`
}

type ApiMessage_CancelRun struct {
	CancelRun *CancelRun `protobuf:"bytes,3,opt,name=cancel_run,json=cancelRun,proto3,oneof"`
}

type ApiMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,4,opt,name=heartbeat,proto3,oneof"`
}

func (*ApiMessage_StartRun) isApiMessage_Payload() {}

func (*ApiMessage_ToolResult) isApiMessage_Payload() {}

func (*ApiMessage_CancelRun) isApiMessage_Payload() {}

func (*ApiMessage_Heartbeat) isApiMessage_Payload() {}

type AgentHello struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	AgentVersion string                 `protobuf:"bytes,1,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	// Model actually backing Axel for this worker, observed rather than configured.
	ModelLabel    string   `protobuf:"bytes,2,opt,name=model_label,json=modelLabel,proto3" json:"model_label,omitempty"`
	Capabilities  []string `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	WorkerId      string   `protobuf:"bytes,4,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentHello) Reset() {
	*x = AgentHello{}
	mi := &file_axioma_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentHello) ProtoMessage() {}

func (x *AgentHello) ProtoReflect() protoreflect.Message {
	mi := &file_axioma_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentHello.ProtoReflect.Descriptor instead.
func (*AgentHello) Descriptor() ([]byte, []int) {
	return file_axioma_proto_rawDescGZIP(), []int{2}
}

func (x *AgentHello) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *AgentHello) GetModelLabel() string {
	if x != nil {
		return x.ModelLabel
	}
	return ""
}

func (x *AgentHello) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *AgentHello) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

type StartRun struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	RunId      string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	TicketId   string                 `protobuf:"bytes,2,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	Title      string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Body       string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	ReporterId string                 `protobuf:"bytes,5,opt,name=reporter_id,json=reporterId,proto3" json:"reporter_id,omitempty"`
	// Empty when the ticket is not about a specific machine.
	DeviceId string `protobuf:"bytes,6,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	// Prior CMDB observations relevant to this ticket, as JSON.
	ContextJson   string `protobuf:"bytes,7,opt,name=context_json,json=contextJson,proto3" json:"context_json,omitempty"`
	RecordType    string `protobuf:"bytes,8,opt,name=record_type,json=recordType,proto3" json:"record_type,omitempty"`
	Impact        string `protobuf:"bytes,9,opt,name=impact,proto3" json:"impact,omitempty"`
	Urgency       string `protobuf:"bytes,10,opt,name=urgency,proto3" json:"urgency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRun) Reset() {
	*x = StartRun{}
	mi := &file_axioma_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRun) ProtoMessage() {}

func (x *StartRun) ProtoReflect() protoreflect.Message {
	mi := &file_axioma_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRun.ProtoReflect.Descriptor instead.
func (*StartRun) Descriptor() ([]byte, []int) {
	return file_axioma_proto_rawDescGZIP(), []int{3}
}

func (x *StartRun) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *StartRun) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

func (x *StartRun) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *StartRun) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *StartRun) GetReporterId() string {
	if x != nil {
		return x.ReporterId
	}
	return ""
}

func (x *StartRun) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *StartRun) GetContextJson() string {
	if x != nil {
		return x.ContextJson
	}
	return ""
}

func (x *StartRun) GetRecordType() string {
	if x != nil {
		return x.RecordType
	}
	return ""
}

func (x *StartRun) GetImpact() string {
	if x != nil {
		return x.Impact
	}
	return ""
}

func (x *StartRun) GetUrgency() string {
	if x != nil {
		return x.Urgency
	}
	return ""
}

type CancelRun struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRun) Reset() {
	*x = CancelRun{}
	mi := &file_axioma_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRun) ProtoMessage() {}

func (x *CancelRun) ProtoReflect() protoreflect.Message {
	mi := &file_axioma_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRun.ProtoReflect.Descriptor instead.
func (*CancelRun) Descriptor() ([]byte, []int) {
	return file_axioma_proto_rawDescGZIP(), []int{4}
}

func (x *CancelRun) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *CancelRun) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// One step of the transcript. Sent as it happens, not batched at the end, so a
// run that hangs still shows how far it got.
type RunUpdate struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RunId          string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Ordinal        uint32                 `protobuf:"varint,2,opt,name=ordinal,proto3" json:"ordinal,omitempty"`
	Kind           RunUpdate_Kind         `protobuf:"varint,3,opt,name=kind,proto3,enum=axioma.v1.RunUpdate_Kind" json:"kind,omitempty"`
	Reasoning      string                 `protobuf:"bytes,4,opt,name=reasoning,proto3" json:"reasoning,omitempty"`
	ToolName       string                 `protobuf:"bytes,5,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	ToolInputJson  string                 `protobuf:"bytes,6,opt,name=tool_input_json,json=toolInputJson,proto3" json:"tool_input_json,omitempty"`
	ToolOutputJson string                 `protobuf:"bytes,7,opt,name=tool_output_json,json=toolOutputJson,proto3" json:"tool_output_json,omitempty"`
	Error          string                 `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	// Set only on KIND_TERMINAL.
	Status           string `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"` // resolved | escalated | failed | exhausted
	Outcome          string `protobuf:"bytes,10,opt,name=outcome,proto3" json:"outcome,omitempty"`
	Evidence         string `protobuf:"bytes,11,opt,name=evidence,proto3" json:"evidence,omitempty"`
	PromptTokens     uint32 `protobuf:"varint,12,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	CompletionTokens uint32 `protobuf:"varint,13,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	Model            string `protobuf:"bytes,14,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RunUpdate) Reset() {
	*x = RunUpdate{}
	mi := &file_axioma_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunUpdate) ProtoMessage() {}

func (x *RunUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_axioma_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunUpdate.ProtoReflect.Descriptor instead.
func (*RunUpdate) Descriptor() ([]byte, []int) {
	return file_axioma_proto_rawDescGZIP(), []int{5}
}

func (x *RunUpdate) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *RunUpdate) GetOrdinal() uint32 {
	if x != nil {
		return x.Ordinal
	}
	return 0
}

func (x *RunUpdate) GetKind() RunUpdate_Kind {
	if x != nil {
		return x.Kind
	}
	return RunUpdate_KIND_UNSPECIFIED
}

func (x *RunUpdate) GetReasoning() string {
	if x != nil {
		return x.Reasoning
	}
	return ""
}

func (x *RunUpdate) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *RunUpdate) GetToolInputJson() string {
	if x != nil {
		return x.ToolInputJson
	}
	return ""
}

func (x *RunUpdate) GetToolOutputJson() string {
	if x != nil {
		return x.ToolOutputJson
	}
	return ""
}

func (x *RunUpdate) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RunUpdate) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RunUpdate) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

func (x *RunUpdate) GetEvidence() string {
	if x != nil {
		return x.Evidence
	}
	return ""
}

func (x *RunUpdate) GetPromptTokens() uint32 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *RunUpdate) GetCompletionTokens() uint32 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

func (x *RunUpdate) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

// The agent asks the API to execute a tool. The agent never touches the
// database, the cluster, or a device directly — the API owns every side effect
// and every persistence path.
type ToolRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RunId             string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	CallId            string                 `protobuf:"bytes,2,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	ToolName          string                 `protobuf:"bytes,3,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	InputJson         string                 `protobuf:"bytes,4,opt,name=input_json,json=inputJson,proto3" json:"input_json,omitempty"`
	SourceStepOrdinal uint32                 `protobuf:"varint,5,opt,name=source_step_ordinal,json=sourceStepOrdinal,proto3" json:"source_step_ordinal,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ToolRequest) Reset() {
	*x = ToolRequest{}
	mi := &file_axioma_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolRequest) ProtoMessage() {}

func (x *ToolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_axioma_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolRequest.ProtoReflect.Descriptor instead.
func (*ToolRequest) Descriptor() ([]byte, []int) {
	return file_axioma_proto_rawDescGZIP(), []int{6}
}

func (x *ToolRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ToolRequest) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *ToolRequest) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ToolRequest) GetInputJson() string {
	if x != nil {
		return x.InputJson
	}
	return ""
}

func (x *ToolRequest) GetSourceStepOrdinal() uint32 {
	if x != nil {
		return x.SourceStepOrdinal
	}
	return 0
}

type ToolResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	CallId        string                 `protobuf:"bytes,2,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	Ok            bool                   `protobuf:"varint,3,opt,name=ok,proto3" json:"ok,omitempty"`
	OutputJson    string                 `protobuf:"bytes,4,opt,name=output_json,json=outputJson,proto3" json:"output_json,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolResult) Reset() {
	*x = ToolResult{}
	mi := &file_axioma_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolResult) ProtoMessage() {}

func (x *ToolResult) ProtoReflect() protoreflect.Message {
	mi := &file_axioma_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolResult.ProtoReflect.Descriptor instead.
func (*ToolResult) Descriptor() ([]byte, []int) {
	return file_axioma_proto_rawDescGZIP(), []int{7}
}

func (x *ToolResult) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ToolResult) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *ToolResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ToolResult) GetOutputJson() string {
	if x != nil {
		return x.OutputJson
	}
	return ""
}

func (x *ToolResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnixMs        int64                  `protobuf:"varint,1,opt,name=unix_ms,json=unixMs,proto3" json:"unix_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_axioma_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_axioma_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_axioma_proto_rawDescGZIP(), []int{8}
}

func (x *Heartbeat) GetUnixMs() int64 {
	if x != nil {
		return x.UnixMs
	}
	return 0
}

type DeviceMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*DeviceMessage_Hello
	//	*DeviceMessage_Result
	//	*DeviceMessage_Heartbeat
	Payload       isDeviceMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceMessage) Reset() {
	*x = DeviceMessage{}
	mi := &file_axioma_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceMessage) ProtoMessage() {}

func (x *DeviceMessage) ProtoReflect() protoreflect.Message {
	mi := &file_axioma_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceMessage.ProtoReflect.Descriptor instead.
func (*DeviceMessage) Descriptor() ([]byte, []int) {
	return file_axioma_proto_rawDescGZIP(), []int{9}
}

func (x *DeviceMessage) GetPayload() isDeviceMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *DeviceMessage) GetHello() *DeviceHello {
	if x != nil {
		if x, ok := x.Payload.(*DeviceMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *DeviceMessage) GetResult() *CommandResult {
	if x != nil {
		if x, ok := x.Payload.(*DeviceMessage_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *DeviceMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*DeviceMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isDeviceMessage_Payload interface {
	isDeviceMessage_Payload()
}

type DeviceMessage_Hello struct {
	Hello *DeviceHello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type DeviceMessage_Result struct {
	Result *CommandResult `protobuf:"bytes,2,opt,name=result,proto3,oneof"`
}

type DeviceMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,3,opt,name=heartbeat,proto3,oneof"`
}

func (*DeviceMessage_Hello) isDeviceMessage_Payload() {}

func (*DeviceMessage_Result) isDeviceMessage_Payload() {}

func (*DeviceMessage_Heartbeat) isDeviceMessage_Payload() {}

type GatewayMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*GatewayMessage_Command
	//	*GatewayMessage_Heartbeat
	//	*GatewayMessage_Enrollment
	Payload       isGatewayMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayMessage) Reset() {
	*x = GatewayMessage{}
	mi := &file_axioma_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayMessage) ProtoMessage() {}

func (x *GatewayMessage) ProtoReflect() protoreflect.Message {
	mi := &file_axioma_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayMessage.ProtoReflect.Descriptor instead.
func (*GatewayMessage) Descriptor() ([]byte, []int) {
	return file_axioma_proto_rawDescGZIP(), []int{10}
}

func (x *GatewayMessage) GetPayload() isGatewayMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *GatewayMessage) GetCommand() *DeviceCommand {
	if x != nil {
		if x, ok := x.Payload.(*GatewayMessage_Command); ok {
			return x.Command
		}
	}
	return nil
}

func (x *GatewayMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*GatewayMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *GatewayMessage) GetEnrollment() *DeviceEnrollment {
	if x != nil {
		if x, ok := x.Payload.(*GatewayMessage_Enrollment); ok {
			return x.Enrollment
		}
	}
	return nil
}

type isGatewayMessage_Payload interface {
	isGatewayMessage_Payload()
}

type GatewayMessage_Command struct {
	Command *DeviceCommand `protobuf:"bytes,1,opt,name=command,proto3,oneof"`
}

type GatewayMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type GatewayMessage_Enrollment struct {
	Enrollment *DeviceEnrollment `protobuf:"bytes,3,opt,name=enrollment,proto3,oneof"`
}

func (*GatewayMessage_Command) isGatewayMessage_Payload() {}

func (*GatewayMessage_Heartbeat) isGatewayMessage_Payload() {}

func (*GatewayMessage_Enrollment) isGatewayMessage_Payload() {}

type DeviceEnrollment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Claimed       bool                   `protobuf:"varint,1,opt,name=claimed,proto3" json:"claimed,omitempty"`
	CodeExpired   bool                   `protobuf:"varint,2,opt,name=code_expired,json=codeExpired,proto3" json:"code_expired,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceEnrollment) Reset() {
	*x = DeviceEnrollment{}
	mi := &file_axioma_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceEnrollment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceEnrollment) ProtoMessage() {}

func (x *DeviceEnrollment) ProtoReflect() protoreflect.Message {
	mi := &file_axioma_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceEnrollment.ProtoReflect.Descriptor instead.
func (*DeviceEnrollment) Descriptor() ([]byte, []int) {
	return file_axioma_proto_rawDescGZIP(), []int{11}
}

func (x *DeviceEnrollment) GetClaimed() bool {
	if x != nil {
		return x.Claimed
	}
	return false
}

func (x *DeviceEnrollment) GetCodeExpired() bool {
	if x != nil {
		return x.CodeExpired
	}
	return false
}

type DeviceHello struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUID minted on first run and persisted to the user profile. Survives
	// restarts and network roaming; dies with the profile, which is the right
	// lifetime for "this person's laptop".
	DeviceId     string `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Hostname     string `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Username     string `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Platform     string `protobuf:"bytes,4,opt,name=platform,proto3" json:"platform,omitempty"`
	Release      string `protobuf:"bytes,5,opt,name=release,proto3" json:"release,omitempty"`
	AgentVersion string `protobuf:"bytes,6,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	// Last sequence the device processed. The gateway replays past it, because a
	// laptop that slept never got to acknowledge anything.
	LastSeenSequence uint64 `protobuf:"varint,7,opt,name=last_seen_sequence,json=lastSeenSequence,proto3" json:"last_seen_sequence,omitempty"`
	EnrolmentCode    string `protobuf:"bytes,8,opt,name=enrolment_code,json=enrolmentCode,proto3" json:"enrolment_code,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DeviceHello) Reset() {
	*x = DeviceHello{}
	mi := &file_axioma_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceHello) ProtoMessage() {}

func (x *DeviceHello) ProtoReflect() protoreflect.Message {
	mi := &file_axioma_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceHello.ProtoReflect.Descriptor instead.
func (*DeviceHello) Descriptor() ([]byte, []int) {
	return file_axioma_proto_rawDescGZIP(), []int{12}
}

func (x *DeviceHello) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeviceHello) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *DeviceHello) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *DeviceHello) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *DeviceHello) GetRelease() string {
	if x != nil {
		return x.Release
	}
	return ""
}

func (x *DeviceHello) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *DeviceHello) GetLastSeenSequence() uint64 {
	if x != nil {
		return x.LastSeenSequence
	}
	return 0
}

func (x *DeviceHello) GetEnrolmentCode() string {
	if x != nil {
		return x.EnrolmentCode
	}
	return ""
}

type DeviceCommand struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	CommandId string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Sequence  uint64                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// Tier one: a named action from a fixed set the device implements. No command
	// string ever crosses this boundary.
	Action     string            `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	Parameters map[string]string `protobuf:"bytes,4,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Tier two: computer-use, when no programmatic path exists. Installed only on
	// machines that need it; absent means the device cannot serve this request.
	ComputerUse    bool   `protobuf:"varint,5,opt,name=computer_use,json=computerUse,proto3" json:"computer_use,omitempty"`
	Objective      string `protobuf:"bytes,6,opt,name=objective,proto3" json:"objective,omitempty"`
	TimeoutSeconds uint32 `protobuf:"varint,7,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeviceCommand) Reset() {
	*x = DeviceCommand{}
	mi := &file_axioma_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceCommand) ProtoMessage() {}

func (x *DeviceCommand) ProtoReflect() protoreflect.Message {
	mi := &file_axioma_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceCommand.ProtoReflect.Descriptor instead.
func (*DeviceCommand) Descriptor() ([]byte, []int) {
	return file_axioma_proto_rawDescGZIP(), []int{13}
}

func (x *DeviceCommand) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *DeviceCommand) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *DeviceCommand) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *DeviceCommand) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *DeviceCommand) GetComputerUse() bool {
	if x != nil {
		return x.ComputerUse
	}
	return false
}

func (x *DeviceCommand) GetObjective() string {
	if x != nil {
		return x.Objective
	}
	return ""
}

func (x *DeviceCommand) GetTimeoutSeconds() uint32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type CommandResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Sequence      uint64                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Ok            bool                   `protobuf:"varint,3,opt,name=ok,proto3" json:"ok,omitempty"`
	OutputJson    string                 `protobuf:"bytes,4,opt,name=output_json,json=outputJson,proto3" json:"output_json,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_axioma_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_axioma_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_axioma_proto_rawDescGZIP(), []int{14}
}

func (x *CommandResult) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandResult) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *CommandResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *CommandResult) GetOutputJson() string {
	if x != nil {
		return x.OutputJson
	}
	return ""
}

func (x *CommandResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_axioma_proto protoreflect.FileDescriptor

const file_axioma_proto_rawDesc = "" +
	"\n" +
	"\faxioma.proto\x12\taxioma.v1\"\xf2\x01\n" +
	"\fAgentMessage\x12-\n" +
	"\x05hello\x18\x01 \x01(\v2\x15.axioma.v1.AgentHelloH\x00R\x05hello\x125\n" +
	"\n" +
	"run_update\x18\x02 \x01(\v2\x14.axioma.v1.RunUpdateH\x00R\trunUpdate\x12;\n" +
	"\ftool_request\x18\x03 \x01(\v2\x16.axioma.v1.ToolRequestH\x00R\vtoolRequest\x124\n" +
	"\theartbeat\x18\x04 \x01(\v2\x14.axioma.v1.HeartbeatH\x00R\theartbeatB\t\n" +
	"\apayload\"\xf2\x01\n" +
	"\n" +
	"ApiMessage\x122\n" +
	"\tstart_run\x18\x01 \x01(\v2\x13.axioma.v1.StartRunH\x00R\bstartRun\x128\n" +
	"\vtool_result\x18\x02 \x01(\v2\x15.axioma.v1.ToolResultH\x00R\n" +
	"toolResult\x125\n" +
	"\n" +
	"cancel_run\x18\x03 \x01(\v2\x14.axioma.v1.CancelRunH\x00R\tcancelRun\x124\n" +
	"\theartbeat\x18\x04 \x01(\v2\x14.axioma.v1.HeartbeatH\x00R\theartbeatB\t\n" +
	"\apayload\"\x93\x01\n" +
	"\n" +
	"AgentHello\x12#\n" +
	"\ragent_version\x18\x01 \x01(\tR\fagentVersion\x12\x1f\n" +
	"\vmodel_label\x18\x02 \x01(\tR\n" +
	"modelLabel\x12\"\n" +
	"\fcapabilities\x18\x03 \x03(\tR\fcapabilities\x12\x1b\n" +
	"\tworker_id\x18\x04 \x01(\tR\bworkerId\"\x9c\x02\n" +
	"\bStartRun\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x1b\n" +
	"\tticket_id\x18\x02 \x01(\tR\bticketId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12\x1f\n" +
	"\vreporter_id\x18\x05 \x01(\tR\n" +
	"reporterId\x12\x1b\n" +
	"\tdevice_id\x18\x06 \x01(\tR\bdeviceId\x12!\n" +
	"\fcontext_json\x18\a \x01(\tR\vcontextJson\x12\x1f\n" +
	"\vrecord_type\x18\b \x01(\tR\n" +
	"recordType\x12\x16\n" +
	"\x06impact\x18\t \x01(\tR\x06impact\x12\x18\n" +
	"\aurgency\x18\n" +
	" \x01(\tR\aurgency\":\n" +
	"\tCancelRun\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\xc2\x04\n" +
	"\tRunUpdate\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x18\n" +
	"\aordinal\x18\x02 \x01(\rR\aordinal\x12-\n" +
	"\x04kind\x18\x03 \x01(\x0e2\x19.axioma.v1.RunUpdate.KindR\x04kind\x12\x1c\n" +
	"\treasoning\x18\x04 \x01(\tR\treasoning\x12\x1b\n" +
	"\ttool_name\x18\x05 \x01(\tR\btoolName\x12&\n" +
	"\x0ftool_input_json\x18\x06 \x01(\tR\rtoolInputJson\x12(\n" +
	"\x10tool_output_json\x18\a \x01(\tR\x0etoolOutputJson\x12\x14\n" +
	"\x05error\x18\b \x01(\tR\x05error\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x12\x18\n" +
	"\aoutcome\x18\n" +
	" \x01(\tR\aoutcome\x12\x1a\n" +
	"\bevidence\x18\v \x01(\tR\bevidence\x12#\n" +
	"\rprompt_tokens\x18\f \x01(\rR\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\r \x01(\rR\x10completionTokens\x12\x14\n" +
	"\x05model\x18\x0e \x01(\tR\x05model\"|\n" +
	"\x04Kind\x12\x14\n" +
	"\x10KIND_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"KIND_THINK\x10\x01\x12\x12\n" +
	"\x0eKIND_TOOL_CALL\x10\x02\x12\x14\n" +
	"\x10KIND_OBSERVATION\x10\x03\x12\x11\n" +
	"\rKIND_DECISION\x10\x04\x12\x11\n" +
	"\rKIND_TERMINAL\x10\x05\"\xa9\x01\n" +
	"\vToolRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x17\n" +
	"\acall_id\x18\x02 \x01(\tR\x06callId\x12\x1b\n" +
	"\ttool_name\x18\x03 \x01(\tR\btoolName\x12\x1d\n" +
	"\n" +
	"input_json\x18\x04 \x01(\tR\tinputJson\x12.\n" +
	"\x13source_step_ordinal\x18\x05 \x01(\rR\x11sourceStepOrdinal\"\x83\x01\n" +
	"\n" +
	"ToolResult\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x17\n" +
	"\acall_id\x18\x02 \x01(\tR\x06callId\x12\x0e\n" +
	"\x02ok\x18\x03 \x01(\bR\x02ok\x12\x1f\n" +
	"\voutput_json\x18\x04 \x01(\tR\n" +
	"outputJson\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"$\n" +
	"\tHeartbeat\x12\x17\n" +
	"\aunix_ms\x18\x01 \x01(\x03R\x06unixMs\"\xb4\x01\n" +
	"\rDeviceMessage\x12.\n" +
	"\x05hello\x18\x01 \x01(\v2\x16.axioma.v1.DeviceHelloH\x00R\x05hello\x122\n" +
	"\x06result\x18\x02 \x01(\v2\x18.axioma.v1.CommandResultH\x00R\x06result\x124\n" +
	"\theartbeat\x18\x03 \x01(\v2\x14.axioma.v1.HeartbeatH\x00R\theartbeatB\t\n" +
	"\apayload\"\xc6\x01\n" +
	"\x0eGatewayMessage\x124\n" +
	"\acommand\x18\x01 \x01(\v2\x18.axioma.v1.DeviceCommandH\x00R\acommand\x124\n" +
	"\theartbeat\x18\x02 \x01(\v2\x14.axioma.v1.HeartbeatH\x00R\theartbeat\x12=\n" +
	"\n" +
	"enrollment\x18\x03 \x01(\v2\x1b.axioma.v1.DeviceEnrollmentH\x00R\n" +
	"enrollmentB\t\n" +
	"\apayload\"O\n" +
	"\x10DeviceEnrollment\x12\x18\n" +
	"\aclaimed\x18\x01 \x01(\bR\aclaimed\x12!\n" +
	"\fcode_expired\x18\x02 \x01(\bR\vcodeExpired\"\x92\x02\n" +
	"\vDeviceHello\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1a\n" +
	"\bplatform\x18\x04 \x01(\tR\bplatform\x12\x18\n" +
	"\arelease\x18\x05 \x01(\tR\arelease\x12#\n" +
	"\ragent_version\x18\x06 \x01(\tR\fagentVersion\x12,\n" +
	"\x12last_seen_sequence\x18\a \x01(\x04R\x10lastSeenSequence\x12%\n" +
	"\x0eenrolment_code\x18\b \x01(\tR\renrolmentCode\"\xd5\x02\n" +
	"\rDeviceCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12H\n" +
	"\n" +
	"parameters\x18\x04 \x03(\v2(.axioma.v1.DeviceCommand.ParametersEntryR\n" +
	"parameters\x12!\n" +
	"\fcomputer_use\x18\x05 \x01(\bR\vcomputerUse\x12\x1c\n" +
	"\tobjective\x18\x06 \x01(\tR\tobjective\x12'\n" +
	"\x0ftimeout_seconds\x18\a \x01(\rR\x0etimeoutSeconds\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x91\x01\n" +
	"\rCommandResult\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\x12\x0e\n" +
	"\x02ok\x18\x03 \x01(\bR\x02ok\x12\x1f\n" +
	"\voutput_json\x18\x04 \x01(\tR\n" +
	"outputJson\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error2M\n" +
	"\fAgentChannel\x12=\n" +
	"\aConnect\x12\x17.axioma.v1.AgentMessage\x1a\x15.axioma.v1.ApiMessage(\x010\x012S\n" +
	"\rDeviceChannel\x12B\n" +
	"\aConnect\x12\x18.axioma.v1.DeviceMessage\x1a\x19.axioma.v1.GatewayMessage(\x010\x01B&Z$github.com/axioma/cli/internal/pb;pbb\x06proto3"

var (
	file_axioma_proto_rawDescOnce sync.Once
	file_axioma_proto_rawDescData []byte
)

func file_axioma_proto_rawDescGZIP() []byte {
	file_axioma_proto_rawDescOnce.Do(func() {
		file_axioma_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_axioma_proto_rawDesc), len(file_axioma_proto_rawDesc)))
	})
	return file_axioma_proto_rawDescData
}

var file_axioma_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_axioma_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_axioma_proto_goTypes = []any{
	(RunUpdate_Kind)(0),      // 0: axioma.v1.RunUpdate.Kind
	(*AgentMessage)(nil),     // 1: axioma.v1.AgentMessage
	(*ApiMessage)(nil),       // 2: axioma.v1.ApiMessage
	(*AgentHello)(nil),       // 3: axioma.v1.AgentHello
	(*StartRun)(nil),         // 4: axioma.v1.StartRun
	(*CancelRun)(nil),        // 5: axioma.v1.CancelRun
	(*RunUpdate)(nil),        // 6: axioma.v1.RunUpdate
	(*ToolRequest)(nil),      // 7: axioma.v1.ToolRequest
	(*ToolResult)(nil),       // 8: axioma.v1.ToolResult
	(*Heartbeat)(nil),        // 9: axioma.v1.Heartbeat
	(*DeviceMessage)(nil),    // 10: axioma.v1.DeviceMessage
	(*GatewayMessage)(nil),   // 11: axioma.v1.GatewayMessage
	(*DeviceEnrollment)(nil), // 12: axioma.v1.DeviceEnrollment
	(*DeviceHello)(nil),      // 13: axioma.v1.DeviceHello
	(*DeviceCommand)(nil),    // 14: axioma.v1.DeviceCommand
	(*CommandResult)(nil),    // 15: axioma.v1.CommandResult
	nil,                      // 16: axioma.v1.DeviceCommand.ParametersEntry
}
var file_axioma_proto_depIdxs = []int32{
	3,  // 0: axioma.v1.AgentMessage.hello:type_name -> axioma.v1.AgentHello
	6,  // 1: axioma.v1.AgentMessage.run_update:type_name -> axioma.v1.RunUpdate
	7,  // 2: axioma.v1.AgentMessage.tool_request:type_name -> axioma.v1.ToolRequest
	9,  // 3: axioma.v1.AgentMessage.heartbeat:type_name -> axioma.v1.Heartbeat
	4,  // 4: axioma.v1.ApiMessage.start_run:type_name -> axioma.v1.StartRun
	8,  // 5: axioma.v1.ApiMessage.tool_result:type_name -> axioma.v1.ToolResult
	5,  // 6: axioma.v1.ApiMessage.cancel_run:type_name -> axioma.v1.CancelRun
	9,  // 7: axioma.v1.ApiMessage.heartbeat:type_name -> axioma.v1.Heartbeat
	0,  // 8: axioma.v1.RunUpdate.kind:type_name -> axioma.v1.RunUpdate.Kind
	13, // 9: axioma.v1.DeviceMessage.hello:type_name -> axioma.v1.DeviceHello
	15, // 10: axioma.v1.DeviceMessage.result:type_name -> axioma.v1.CommandResult
	9,  // 11: axioma.v1.DeviceMessage.heartbeat:type_name -> axioma.v1.Heartbeat
	14, // 12: axioma.v1.GatewayMessage.command:type_name -> axioma.v1.DeviceCommand
	9,  // 13: axioma.v1.GatewayMessage.heartbeat:type_name -> axioma.v1.Heartbeat
	12, // 14: axioma.v1.GatewayMessage.enrollment:type_name -> axioma.v1.DeviceEnrollment
	16, // 15: axioma.v1.DeviceCommand.parameters:type_name -> axioma.v1.DeviceCommand.ParametersEntry
	1,  // 16: axioma.v1.AgentChannel.Connect:input_type -> axioma.v1.AgentMessage
	10, // 17: axioma.v1.DeviceChannel.Connect:input_type -> axioma.v1.DeviceMessage
	2,  // 18: axioma.v1.AgentChannel.Connect:output_type -> axioma.v1.ApiMessage
	11, // 19: axioma.v1.DeviceChannel.Connect:output_type -> axioma.v1.GatewayMessage
	18, // [18:20] is the sub-list for method output_type
	16, // [16:18] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_axioma_proto_init() }
func file_axioma_proto_init() {
	if File_axioma_proto != nil {
		return
	}
	file_axioma_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentMessage_Hello)(nil),
		(*AgentMessage_RunUpdate)(nil),
		(*AgentMessage_ToolRequest)(nil),
		(*AgentMessage_Heartbeat)(nil),
	}
	file_axioma_proto_msgTypes[1].OneofWrappers = []any{
		(*ApiMessage_StartRun)(nil),
		(*ApiMessage_ToolResult)(nil),
		(*ApiMessage_CancelRun)(nil),
		(*ApiMessage_Heartbeat)(nil),
	}
	file_axioma_proto_msgTypes[9].OneofWrappers = []any{
		(*DeviceMessage_Hello)(nil),
		(*DeviceMessage_Result)(nil),
		(*DeviceMessage_Heartbeat)(nil),
	}
	file_axioma_proto_msgTypes[10].OneofWrappers = []any{
		(*GatewayMessage_Command)(nil),
		(*GatewayMessage_Heartbeat)(nil),
		(*GatewayMessage_Enrollment)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_axioma_proto_rawDesc), len(file_axioma_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_axioma_proto_goTypes,
		DependencyIndexes: file_axioma_proto_depIdxs,
		EnumInfos:         file_axioma_proto_enumTypes,
		MessageInfos:      file_axioma_proto_msgTypes,
	}.Build()
	File_axioma_proto = out.File
	file_axioma_proto_goTypes = nil
	file_axioma_proto_depIdxs = nil
}
