// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.35.1
// source: axioma.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Canonical fixed action vocabulary. DeviceCommand.action stays a string for wire
// compatibility; parity tests keep dispatch implementations aligned with this enum.
type DeviceAction int32

const (
	DeviceAction_DEVICE_ACTION_UNSPECIFIED               DeviceAction = 0
	DeviceAction_DEVICE_ACTION_FLUSH_DNS                 DeviceAction = 1
	DeviceAction_DEVICE_ACTION_RENEW_DHCP_LEASE          DeviceAction = 2
	DeviceAction_DEVICE_ACTION_CLEAR_PROXY_OVERRIDE      DeviceAction = 3
	DeviceAction_DEVICE_ACTION_RESET_CREDENTIAL_CACHE    DeviceAction = 4
	DeviceAction_DEVICE_ACTION_RESTART_USER_PROCESS      DeviceAction = 5
	DeviceAction_DEVICE_ACTION_DISABLE_PROXY             DeviceAction = 6
	DeviceAction_DEVICE_ACTION_REFRESH_CERTIFICATE_STORE DeviceAction = 7
	DeviceAction_DEVICE_ACTION_CLEAR_TEMP_FILES          DeviceAction = 8
	DeviceAction_DEVICE_ACTION_CLEAR_OUTLOOK_CACHE       DeviceAction = 9
	DeviceAction_DEVICE_ACTION_CLEAR_TEAMS_CACHE         DeviceAction = 10
	DeviceAction_DEVICE_ACTION_CLEAR_ICON_CACHE          DeviceAction = 11
	DeviceAction_DEVICE_ACTION_CLEAR_PRINT_QUEUE         DeviceAction = 12
	DeviceAction_DEVICE_ACTION_GUI_INVOKE_CONTROL        DeviceAction = 13
	DeviceAction_DEVICE_ACTION_GUI_SET_CONTROL_VALUE     DeviceAction = 14
	DeviceAction_DEVICE_ACTION_GUI_TOGGLE_CONTROL        DeviceAction = 15
	DeviceAction_DEVICE_ACTION_GUI_SELECT_ITEM           DeviceAction = 16
	DeviceAction_DEVICE_ACTION_GUI_EXPAND_CONTROL        DeviceAction = 17
	// Dispatched by the API from an approved proposal, never selected by the
	// model. It is absent from the agent and API action enums on purpose.
	DeviceAction_DEVICE_ACTION_RUN_COMMAND DeviceAction = 18
)

// Enum value maps for DeviceAction.
var (
	DeviceAction_name = map[int32]string{
		0:  "DEVICE_ACTION_UNSPECIFIED",
		1:  "DEVICE_ACTION_FLUSH_DNS",
		2:  "DEVICE_ACTION_RENEW_DHCP_LEASE",
		3:  "DEVICE_ACTION_CLEAR_PROXY_OVERRIDE",
		4:  "DEVICE_ACTION_RESET_CREDENTIAL_CACHE",
		5:  "DEVICE_ACTION_RESTART_USER_PROCESS",
		6:  "DEVICE_ACTION_DISABLE_PROXY",
		7:  "DEVICE_ACTION_REFRESH_CERTIFICATE_STORE",
		8:  "DEVICE_ACTION_CLEAR_TEMP_FILES",
		9:  "DEVICE_ACTION_CLEAR_OUTLOOK_CACHE",
		10: "DEVICE_ACTION_CLEAR_TEAMS_CACHE",
		11: "DEVICE_ACTION_CLEAR_ICON_CACHE",
		12: "DEVICE_ACTION_CLEAR_PRINT_QUEUE",
		13: "DEVICE_ACTION_GUI_INVOKE_CONTROL",
		14: "DEVICE_ACTION_GUI_SET_CONTROL_VALUE",
		15: "DEVICE_ACTION_GUI_TOGGLE_CONTROL",
		16: "DEVICE_ACTION_GUI_SELECT_ITEM",
		17: "DEVICE_ACTION_GUI_EXPAND_CONTROL",
		18: "DEVICE_ACTION_RUN_COMMAND",
	}
	DeviceAction_value = map[string]int32{
		"DEVICE_ACTION_UNSPECIFIED":               0,
		"DEVICE_ACTION_FLUSH_DNS":                 1,
		"DEVICE_ACTION_RENEW_DHCP_LEASE":          2,
		"DEVICE_ACTION_CLEAR_PROXY_OVERRIDE":      3,
		"DEVICE_ACTION_RESET_CREDENTIAL_CACHE":    4,
		"DEVICE_ACTION_RESTART_USER_PROCESS":      5,
		"DEVICE_ACTION_DISABLE_PROXY":             6,
		"DEVICE_ACTION_REFRESH_CERTIFICATE_STORE": 7,
		"DEVICE_ACTION_CLEAR_TEMP_FILES":          8,
		"DEVICE_ACTION_CLEAR_OUTLOOK_CACHE":       9,
		"DEVICE_ACTION_CLEAR_TEAMS_CACHE":         10,
		"DEVICE_ACTION_CLEAR_ICON_CACHE":          11,
		"DEVICE_ACTION_CLEAR_PRINT_QUEUE":         12,
		"DEVICE_ACTION_GUI_INVOKE_CONTROL":        13,
		"DEVICE_ACTION_GUI_SET_CONTROL_VALUE":     14,
		"DEVICE_ACTION_GUI_TOGGLE_CONTROL":        15,
		"DEVICE_ACTION_GUI_SELECT_ITEM":           16,
		"DEVICE_ACTION_GUI_EXPAND_CONTROL":        17,
		"DEVICE_ACTION_RUN_COMMAND":               18,
	}
)

func (x DeviceAction) Enum() *DeviceAction {
	p := new(DeviceAction)
	*p = x
	return p
}

func (x DeviceAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceAction) Descriptor() protoreflect.EnumDescriptor {
	return file_axioma_proto_enumTypes[0].Descriptor()
}

func (DeviceAction) Type() protoreflect.EnumType {
	return &file_axioma_proto_enumTypes[0]
}

func (x DeviceAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceAction.Descriptor instead.
func (DeviceAction) EnumDescriptor() ([]byte, []int) {
	return file_axioma_proto_rawDescGZIP(), []int{0}
}

// Canonical fixed facet vocabulary — the observable state each action is verified
// against. DeviceCommand.parameters["facets"] stays a JSON string for wire
// compatibility; parity tests keep facet implementations aligned with this enum.
type DeviceFacet int32

const (
	DeviceFacet_DEVICE_FACET_UNSPECIFIED  DeviceFacet = 0
	DeviceFacet_DEVICE_FACET_RESOLVER     DeviceFacet = 1
	DeviceFacet_DEVICE_FACET_ADAPTERS     DeviceFacet = 2
	DeviceFacet_DEVICE_FACET_REACHABILITY DeviceFacet = 3
	DeviceFacet_DEVICE_FACET_PROXY        DeviceFacet = 4
	DeviceFacet_DEVICE_FACET_IDENTITY     DeviceFacet = 5
	DeviceFacet_DEVICE_FACET_PROCESSES    DeviceFacet = 6
	DeviceFacet_DEVICE_FACET_CERTIFICATES DeviceFacet = 7
	DeviceFacet_DEVICE_FACET_STORAGE      DeviceFacet = 8
	DeviceFacet_DEVICE_FACET_APP_CACHE    DeviceFacet = 9
	DeviceFacet_DEVICE_FACET_PRINTING     DeviceFacet = 10
	DeviceFacet_DEVICE_FACET_SCREEN       DeviceFacet = 11
)

// Enum value maps for DeviceFacet.
var (
	DeviceFacet_name = map[int32]string{
		0:  "DEVICE_FACET_UNSPECIFIED",
		1:  "DEVICE_FACET_RESOLVER",
		2:  "DEVICE_FACET_ADAPTERS",
		3:  "DEVICE_FACET_REACHABILITY",
		4:  "DEVICE_FACET_PROXY",
		5:  "DEVICE_FACET_IDENTITY",
		6:  "DEVICE_FACET_PROCESSES",
		7:  "DEVICE_FACET_CERTIFICATES",
		8:  "DEVICE_FACET_STORAGE",
		9:  "DEVICE_FACET_APP_CACHE",
		10: "DEVICE_FACET_PRINTING",
		11: "DEVICE_FACET_SCREEN",
	}
	DeviceFacet_value = map[string]int32{
		"DEVICE_FACET_UNSPECIFIED":  0,
		"DEVICE_FACET_RESOLVER":     1,
		"DEVICE_FACET_ADAPTERS":     2,
		"DEVICE_FACET_REACHABILITY": 3,
		"DEVICE_FACET_PROXY":        4,
		"DEVICE_FACET_IDENTITY":     5,
		"DEVICE_FACET_PROCESSES":    6,
		"DEVICE_FACET_CERTIFICATES": 7,
		"DEVICE_FACET_STORAGE":      8,
		"DEVICE_FACET_APP_CACHE":    9,
		"DEVICE_FACET_PRINTING":     10,
		"DEVICE_FACET_SCREEN":       11,
	}
)

func (x DeviceFacet) Enum() *DeviceFacet {
	p := new(DeviceFacet)
	*p = x
	return p
}

func (x DeviceFacet) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceFacet) Descriptor() protoreflect.EnumDescriptor {
	return file_axioma_proto_enumTypes[1].Descriptor()
}

func (DeviceFacet) Type() protoreflect.EnumType {
	return &file_axioma_proto_enumTypes[1]
}

func (x DeviceFacet) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceFacet.Descriptor instead.
func (DeviceFacet) EnumDescriptor() ([]byte, []int) {
	return file_axioma_proto_rawDescGZIP(), []int{1}
}

type RunUpdate_Kind int32

const (
	RunUpdate_KIND_UNSPECIFIED RunUpdate_Kind = 0
	RunUpdate_KIND_THINK       RunUpdate_Kind = 1
	RunUpdate_KIND_TOOL_CALL   RunUpdate_Kind = 2
	RunUpdate_KIND_OBSERVATION RunUpdate_Kind = 3
	RunUpdate_KIND_DECISION    RunUpdate_Kind = 4
	RunUpdate_KIND_TERMINAL    RunUpdate_Kind = 5
)

// Enum value maps for RunUpdate_Kind.
var (
	RunUpdate_Kind_name = map[int32]string{
		0: "KIND_UNSPECIFIED",
		1: "KIND_THINK",
		2: "KIND_TOOL_CALL",
		3: "KIND_OBSERVATION",
		4: "KIND_DECISION",
		5: "KIND_TERMINAL",
	}
	RunUpdate_Kind_value = map[string]int32{
		"KIND_UNSPECIFIED": 0,
		"KIND_THINK":       1,
		"KIND_TOOL_CALL":   2,
		"KIND_OBSERVATION": 3,
		"KIND_DECISION":    4,
		"KIND_TERMINAL":    5,
	}
)

func (x RunUpdate_Kind) Enum() *RunUpdate_Kind {
	p := new(RunUpdate_Kind)
	*p = x
	return p
}

func (x RunUpdate_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RunUpdate_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_axioma_proto_enumTypes[2].Descriptor()
}

func (RunUpdate_Kind) Type() protoreflect.EnumType {
	return &file_axioma_proto_enumTypes[2]
}

func (x RunUpdate_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RunUpdate_Kind.Descriptor instead.
func (RunUpdate_Kind) EnumDescriptor() ([]byte, []int) {
	return file_axioma_proto_rawDescGZIP(), []int{7, 0}
}

type AgentMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentMessage_Hello
	//	*AgentMessage_RunUpdate
	//	*AgentMessage_ToolRequest
	//	*AgentMessage_Heartbeat
	//	*AgentMessage_RunAccepted
	Payload       isAgentMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_axioma_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_axioma_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_axioma_proto_rawDescGZIP(), []int{0}
}

func (x *AgentMessage) GetPayload() isAgentMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentMessage) GetHello() *AgentHello {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *AgentMessage) GetRunUpdate() *RunUpdate {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_RunUpdate); ok {
			return x.RunUpdate
		}
	}
	return nil
}

func (x *AgentMessage) GetToolRequest() *ToolRequest {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_ToolRequest); ok {
			return x.ToolRequest
		}
	}
	return nil
}

func (x *AgentMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentMessage) GetRunAccepted() *RunAccepted {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_RunAccepted); ok {
			return x.RunAccepted
		}
	}
	return nil
}

type isAgentMessage_Payload interface {
	isAgentMessage_Payload()
}

type AgentMessage_Hello struct {
	Hello *AgentHello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type AgentMessage_RunUpdate struct {
	RunUpdate *RunUpdate `protobuf:"bytes,2,opt,name=run_update,json=runUpdate,proto3,oneof"`
}

type AgentMessage_ToolRequest struct {
	ToolRequest *ToolRequest `protobuf:"bytes,3,opt,name=tool_request,json=toolRequest,proto3,oneof"`
}

type AgentMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,4,opt,name=heartbeat,proto3,oneof"`
}

type AgentMessage_RunAccepted struct {
	RunAccepted *RunAccepted `protobuf:"bytes,5,opt,name=run_accepted,json=runAccepted,proto3,oneof"`
}

func (*AgentMessage_Hello) isAgentMessage_Payload() {}

func (*AgentMessage_RunUpdate) isAgentMessage_Payload() {}

func (*AgentMessage_ToolRequest) isAgentMessage_Payload() {}

func (*AgentMessage_Heartbeat) isAgentMessage_Payload() {}

func (*AgentMessage_RunAccepted) isAgentMessage_Payload() {}

type RunAccepted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunAccepted) Reset() {
	*x = RunAccepted{}
	mi := &file_axioma_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunAccepted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunAccepted) ProtoMessage() {}

func (x *RunAccepted) ProtoReflect() protoreflect.Message {
	mi := &file_axioma_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunAccepted.ProtoReflect.Descriptor instead.
func (*RunAccepted) Descriptor() ([]byte, []int) {
	return file_axioma_proto_rawDescGZIP(), []int{1}
}

func (x *RunAccepted) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type ApiMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ApiMessage_StartRun
	//	*ApiMessage_ToolResult
	//	*ApiMessage_CancelRun
	//	*ApiMessage_Heartbeat
	//	*ApiMessage_TerminalAck
	Payload       isApiMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiMessage) Reset() {
	*x = ApiMessage{}
	mi := &file_axioma_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiMessage) ProtoMessage() {}

func (x *ApiMessage) ProtoReflect() protoreflect.Message {
	mi := &file_axioma_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiMessage.ProtoReflect.Descriptor instead.
func (*ApiMessage) Descriptor() ([]byte, []int) {
	return file_axioma_proto_rawDescGZIP(), []int{2}
}

func (x *ApiMessage) GetPayload() isApiMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ApiMessage) GetStartRun() *StartRun {
	if x != nil {
		if x, ok := x.Payload.(*ApiMessage_StartRun); ok {
			return x.StartRun
		}
	}
	return nil
}

func (x *ApiMessage) GetToolResult() *ToolResult {
	if x != nil {
		if x, ok := x.Payload.(*ApiMessage_ToolResult); ok {
			return x.ToolResult
		}
	}
	return nil
}

func (x *ApiMessage) GetCancelRun() *CancelRun {
	if x != nil {
		if x, ok := x.Payload.(*ApiMessage_CancelRun); ok {
			return x.CancelRun
		}
	}
	return nil
}

func (x *ApiMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*ApiMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *ApiMessage) GetTerminalAck() *TerminalAck {
	if x != nil {
		if x, ok := x.Payload.(*ApiMessage_TerminalAck); ok {
			return x.TerminalAck
		}
	}
	return nil
}

type isApiMessage_Payload interface {
	isApiMessage_Payload()
}

type ApiMessage_StartRun struct {
	StartRun *StartRun `protobuf:"bytes,1,opt,name=start_run,json=startRun,proto3,oneof"`
}

type ApiMessage_ToolResult struct {
	ToolResult *ToolResult `protobuf:"bytes,2,opt,name=tool_result,json=toolResult,proto3,oneof"`
}

type ApiMessage_CancelRun struct {
	CancelRun *CancelRun `protobuf:"bytes,3,opt,name=cancel_run,json=cancelRun,proto3,oneof"`
}

type ApiMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,4,opt,name=heartbeat,proto3,oneof"`
}

type ApiMessage_TerminalAck struct {
	TerminalAck *TerminalAck `protobuf:"bytes,5,opt,name=terminal_ack,json=terminalAck,proto3,oneof"`
}

func (*ApiMessage_StartRun) isApiMessage_Payload() {}

func (*ApiMessage_ToolResult) isApiMessage_Payload() {}

func (*ApiMessage_CancelRun) isApiMessage_Payload() {}

func (*ApiMessage_Heartbeat) isApiMessage_Payload() {}

func (*ApiMessage_TerminalAck) isApiMessage_Payload() {}

type TerminalAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Ordinal       uint32                 `protobuf:"varint,2,opt,name=ordinal,proto3" json:"ordinal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalAck) Reset() {
	*x = TerminalAck{}
	mi := &file_axioma_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalAck) ProtoMessage() {}

func (x *TerminalAck) ProtoReflect() protoreflect.Message {
	mi := &file_axioma_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalAck.ProtoReflect.Descriptor instead.
func (*TerminalAck) Descriptor() ([]byte, []int) {
	return file_axioma_proto_rawDescGZIP(), []int{3}
}

func (x *TerminalAck) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *TerminalAck) GetOrdinal() uint32 {
	if x != nil {
		return x.Ordinal
	}
	return 0
}

type AgentHello struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	AgentVersion string                 `protobuf:"bytes,1,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	// Model actually backing Axel for this worker, observed rather than configured.
	ModelLabel   string   `protobuf:"bytes,2,opt,name=model_label,json=modelLabel,proto3" json:"model_label,omitempty"`
	Capabilities []string `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	WorkerId     string   `protobuf:"bytes,4,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	// Shared secret proving this stream is a worker the operator deployed. The
	// channel carries ticket text, reporter identity and tool execution, and the
	// gateway port is reachable by every enrolled laptop, so a worker id alone is
	// not an identity. Compared against AXIOMA_AGENT_TOKEN on the gateway.
	Credential    string `protobuf:"bytes,5,opt,name=credential,proto3" json:"credential,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentHello) Reset() {
	*x = AgentHello{}
	mi := &file_axioma_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentHello) ProtoMessage() {}

func (x *AgentHello) ProtoReflect() protoreflect.Message {
	mi := &file_axioma_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentHello.ProtoReflect.Descriptor instead.
func (*AgentHello) Descriptor() ([]byte, []int) {
	return file_axioma_proto_rawDescGZIP(), []int{4}
}

func (x *AgentHello) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *AgentHello) GetModelLabel() string {
	if x != nil {
		return x.ModelLabel
	}
	return ""
}

func (x *AgentHello) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *AgentHello) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *AgentHello) GetCredential() string {
	if x != nil {
		return x.Credential
	}
	return ""
}

type StartRun struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	RunId      string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	TicketId   string                 `protobuf:"bytes,2,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	Title      string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Body       string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	ReporterId string                 `protobuf:"bytes,5,opt,name=reporter_id,json=reporterId,proto3" json:"reporter_id,omitempty"`
	// Empty when the ticket is not about a specific machine.
	DeviceId string `protobuf:"bytes,6,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	// Prior CMDB observations relevant to this ticket, as JSON.
	ContextJson string `protobuf:"bytes,7,opt,name=context_json,json=contextJson,proto3" json:"context_json,omitempty"`
	RecordType  string `protobuf:"bytes,8,opt,name=record_type,json=recordType,proto3" json:"record_type,omitempty"`
	Impact      string `protobuf:"bytes,9,opt,name=impact,proto3" json:"impact,omitempty"`
	Urgency     string `protobuf:"bytes,10,opt,name=urgency,proto3" json:"urgency,omitempty"`
	Priority    string `protobuf:"bytes,11,opt,name=priority,proto3" json:"priority,omitempty"`
	// Ticket ingestion provenance (for example portal, employee_email, monitoring).
	Origin string `protobuf:"bytes,12,opt,name=origin,proto3" json:"origin,omitempty"`
	// Server-resolved target environment. The agent may not infer this from ticket prose.
	Environment        string `protobuf:"bytes,13,opt,name=environment,proto3" json:"environment,omitempty"`
	ReporterName       string `protobuf:"bytes,14,opt,name=reporter_name,json=reporterName,proto3" json:"reporter_name,omitempty"`
	ReporterJobTitle   string `protobuf:"bytes,15,opt,name=reporter_job_title,json=reporterJobTitle,proto3" json:"reporter_job_title,omitempty"`
	ReporterDepartment string `protobuf:"bytes,16,opt,name=reporter_department,json=reporterDepartment,proto3" json:"reporter_department,omitempty"`
	ReporterManager    string `protobuf:"bytes,17,opt,name=reporter_manager,json=reporterManager,proto3" json:"reporter_manager,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StartRun) Reset() {
	*x = StartRun{}
	mi := &file_axioma_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRun) ProtoMessage() {}

func (x *StartRun) ProtoReflect() protoreflect.Message {
	mi := &file_axioma_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRun.ProtoReflect.Descriptor instead.
func (*StartRun) Descriptor() ([]byte, []int) {
	return file_axioma_proto_rawDescGZIP(), []int{5}
}

func (x *StartRun) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *StartRun) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

func (x *StartRun) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *StartRun) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *StartRun) GetReporterId() string {
	if x != nil {
		return x.ReporterId
	}
	return ""
}

func (x *StartRun) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *StartRun) GetContextJson() string {
	if x != nil {
		return x.ContextJson
	}
	return ""
}

func (x *StartRun) GetRecordType() string {
	if x != nil {
		return x.RecordType
	}
	return ""
}

func (x *StartRun) GetImpact() string {
	if x != nil {
		return x.Impact
	}
	return ""
}

func (x *StartRun) GetUrgency() string {
	if x != nil {
		return x.Urgency
	}
	return ""
}

func (x *StartRun) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *StartRun) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *StartRun) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *StartRun) GetReporterName() string {
	if x != nil {
		return x.ReporterName
	}
	return ""
}

func (x *StartRun) GetReporterJobTitle() string {
	if x != nil {
		return x.ReporterJobTitle
	}
	return ""
}

func (x *StartRun) GetReporterDepartment() string {
	if x != nil {
		return x.ReporterDepartment
	}
	return ""
}

func (x *StartRun) GetReporterManager() string {
	if x != nil {
		return x.ReporterManager
	}
	return ""
}

type CancelRun struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRun) Reset() {
	*x = CancelRun{}
	mi := &file_axioma_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRun) ProtoMessage() {}

func (x *CancelRun) ProtoReflect() protoreflect.Message {
	mi := &file_axioma_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRun.ProtoReflect.Descriptor instead.
func (*CancelRun) Descriptor() ([]byte, []int) {
	return file_axioma_proto_rawDescGZIP(), []int{6}
}

func (x *CancelRun) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *CancelRun) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// One step of the transcript. Sent as it happens, not batched at the end, so a
// run that hangs still shows how far it got.
type RunUpdate struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RunId          string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Ordinal        uint32                 `protobuf:"varint,2,opt,name=ordinal,proto3" json:"ordinal,omitempty"`
	Kind           RunUpdate_Kind         `protobuf:"varint,3,opt,name=kind,proto3,enum=axioma.v1.RunUpdate_Kind" json:"kind,omitempty"`
	Reasoning      string                 `protobuf:"bytes,4,opt,name=reasoning,proto3" json:"reasoning,omitempty"`
	ToolName       string                 `protobuf:"bytes,5,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	ToolInputJson  string                 `protobuf:"bytes,6,opt,name=tool_input_json,json=toolInputJson,proto3" json:"tool_input_json,omitempty"`
	ToolOutputJson string                 `protobuf:"bytes,7,opt,name=tool_output_json,json=toolOutputJson,proto3" json:"tool_output_json,omitempty"`
	Error          string                 `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	// Set only on KIND_TERMINAL.
	Status           string `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"` // resolved | escalated | failed | exhausted
	Outcome          string `protobuf:"bytes,10,opt,name=outcome,proto3" json:"outcome,omitempty"`
	Evidence         string `protobuf:"bytes,11,opt,name=evidence,proto3" json:"evidence,omitempty"`
	PromptTokens     uint32 `protobuf:"varint,12,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	CompletionTokens uint32 `protobuf:"varint,13,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	Model            string `protobuf:"bytes,14,opt,name=model,proto3" json:"model,omitempty"`
	ResolutionCode   string `protobuf:"bytes,15,opt,name=resolution_code,json=resolutionCode,proto3" json:"resolution_code,omitempty"` // resolved terminals only
	// Informational messages that are not failures (e.g. transient provider
	// retries). Empty means absent.
	Notice string `protobuf:"bytes,16,opt,name=notice,proto3" json:"notice,omitempty"`
	// Presentation tone for the evidence alert:
	// success | warning | destructive | neutral
	EvidenceTone  string `protobuf:"bytes,17,opt,name=evidence_tone,json=evidenceTone,proto3" json:"evidence_tone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunUpdate) Reset() {
	*x = RunUpdate{}
	mi := &file_axioma_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunUpdate) ProtoMessage() {}

func (x *RunUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_axioma_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunUpdate.ProtoReflect.Descriptor instead.
func (*RunUpdate) Descriptor() ([]byte, []int) {
	return file_axioma_proto_rawDescGZIP(), []int{7}
}

func (x *RunUpdate) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *RunUpdate) GetOrdinal() uint32 {
	if x != nil {
		return x.Ordinal
	}
	return 0
}

func (x *RunUpdate) GetKind() RunUpdate_Kind {
	if x != nil {
		return x.Kind
	}
	return RunUpdate_KIND_UNSPECIFIED
}

func (x *RunUpdate) GetReasoning() string {
	if x != nil {
		return x.Reasoning
	}
	return ""
}

func (x *RunUpdate) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *RunUpdate) GetToolInputJson() string {
	if x != nil {
		return x.ToolInputJson
	}
	return ""
}

func (x *RunUpdate) GetToolOutputJson() string {
	if x != nil {
		return x.ToolOutputJson
	}
	return ""
}

func (x *RunUpdate) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RunUpdate) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RunUpdate) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

func (x *RunUpdate) GetEvidence() string {
	if x != nil {
		return x.Evidence
	}
	return ""
}

func (x *RunUpdate) GetPromptTokens() uint32 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *RunUpdate) GetCompletionTokens() uint32 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

func (x *RunUpdate) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *RunUpdate) GetResolutionCode() string {
	if x != nil {
		return x.ResolutionCode
	}
	return ""
}

func (x *RunUpdate) GetNotice() string {
	if x != nil {
		return x.Notice
	}
	return ""
}

func (x *RunUpdate) GetEvidenceTone() string {
	if x != nil {
		return x.EvidenceTone
	}
	return ""
}

// The agent asks the API to execute a tool. The agent never touches the
// database, the cluster, or a device directly — the API owns every side effect
// and every persistence path.
type ToolRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RunId             string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	CallId            string                 `protobuf:"bytes,2,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	ToolName          string                 `protobuf:"bytes,3,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	InputJson         string                 `protobuf:"bytes,4,opt,name=input_json,json=inputJson,proto3" json:"input_json,omitempty"`
	SourceStepOrdinal uint32                 `protobuf:"varint,5,opt,name=source_step_ordinal,json=sourceStepOrdinal,proto3" json:"source_step_ordinal,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ToolRequest) Reset() {
	*x = ToolRequest{}
	mi := &file_axioma_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolRequest) ProtoMessage() {}

func (x *ToolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_axioma_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolRequest.ProtoReflect.Descriptor instead.
func (*ToolRequest) Descriptor() ([]byte, []int) {
	return file_axioma_proto_rawDescGZIP(), []int{8}
}

func (x *ToolRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ToolRequest) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *ToolRequest) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ToolRequest) GetInputJson() string {
	if x != nil {
		return x.InputJson
	}
	return ""
}

func (x *ToolRequest) GetSourceStepOrdinal() uint32 {
	if x != nil {
		return x.SourceStepOrdinal
	}
	return 0
}

type ToolResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	CallId        string                 `protobuf:"bytes,2,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	Ok            bool                   `protobuf:"varint,3,opt,name=ok,proto3" json:"ok,omitempty"`
	OutputJson    string                 `protobuf:"bytes,4,opt,name=output_json,json=outputJson,proto3" json:"output_json,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolResult) Reset() {
	*x = ToolResult{}
	mi := &file_axioma_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolResult) ProtoMessage() {}

func (x *ToolResult) ProtoReflect() protoreflect.Message {
	mi := &file_axioma_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolResult.ProtoReflect.Descriptor instead.
func (*ToolResult) Descriptor() ([]byte, []int) {
	return file_axioma_proto_rawDescGZIP(), []int{9}
}

func (x *ToolResult) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ToolResult) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *ToolResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ToolResult) GetOutputJson() string {
	if x != nil {
		return x.OutputJson
	}
	return ""
}

func (x *ToolResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnixMs        int64                  `protobuf:"varint,1,opt,name=unix_ms,json=unixMs,proto3" json:"unix_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_axioma_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_axioma_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_axioma_proto_rawDescGZIP(), []int{10}
}

func (x *Heartbeat) GetUnixMs() int64 {
	if x != nil {
		return x.UnixMs
	}
	return 0
}

type DeviceMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*DeviceMessage_Hello
	//	*DeviceMessage_Result
	//	*DeviceMessage_Heartbeat
	//	*DeviceMessage_Inventory
	Payload       isDeviceMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceMessage) Reset() {
	*x = DeviceMessage{}
	mi := &file_axioma_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceMessage) ProtoMessage() {}

func (x *DeviceMessage) ProtoReflect() protoreflect.Message {
	mi := &file_axioma_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceMessage.ProtoReflect.Descriptor instead.
func (*DeviceMessage) Descriptor() ([]byte, []int) {
	return file_axioma_proto_rawDescGZIP(), []int{11}
}

func (x *DeviceMessage) GetPayload() isDeviceMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *DeviceMessage) GetHello() *DeviceHello {
	if x != nil {
		if x, ok := x.Payload.(*DeviceMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *DeviceMessage) GetResult() *CommandResult {
	if x != nil {
		if x, ok := x.Payload.(*DeviceMessage_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *DeviceMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*DeviceMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *DeviceMessage) GetInventory() *InventoryReport {
	if x != nil {
		if x, ok := x.Payload.(*DeviceMessage_Inventory); ok {
			return x.Inventory
		}
	}
	return nil
}

type isDeviceMessage_Payload interface {
	isDeviceMessage_Payload()
}

type DeviceMessage_Hello struct {
	Hello *DeviceHello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type DeviceMessage_Result struct {
	Result *CommandResult `protobuf:"bytes,2,opt,name=result,proto3,oneof"`
}

type DeviceMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,3,opt,name=heartbeat,proto3,oneof"`
}

type DeviceMessage_Inventory struct {
	Inventory *InventoryReport `protobuf:"bytes,4,opt,name=inventory,proto3,oneof"`
}

func (*DeviceMessage_Hello) isDeviceMessage_Payload() {}

func (*DeviceMessage_Result) isDeviceMessage_Payload() {}

func (*DeviceMessage_Heartbeat) isDeviceMessage_Payload() {}

func (*DeviceMessage_Inventory) isDeviceMessage_Payload() {}

type InventoryReport struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ReportId        string                 `protobuf:"bytes,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	CollectedUnixMs int64                  `protobuf:"varint,2,opt,name=collected_unix_ms,json=collectedUnixMs,proto3" json:"collected_unix_ms,omitempty"`
	InventoryJson   string                 `protobuf:"bytes,3,opt,name=inventory_json,json=inventoryJson,proto3" json:"inventory_json,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InventoryReport) Reset() {
	*x = InventoryReport{}
	mi := &file_axioma_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryReport) ProtoMessage() {}

func (x *InventoryReport) ProtoReflect() protoreflect.Message {
	mi := &file_axioma_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryReport.ProtoReflect.Descriptor instead.
func (*InventoryReport) Descriptor() ([]byte, []int) {
	return file_axioma_proto_rawDescGZIP(), []int{12}
}

func (x *InventoryReport) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

func (x *InventoryReport) GetCollectedUnixMs() int64 {
	if x != nil {
		return x.CollectedUnixMs
	}
	return 0
}

func (x *InventoryReport) GetInventoryJson() string {
	if x != nil {
		return x.InventoryJson
	}
	return ""
}

type GatewayMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*GatewayMessage_Command
	//	*GatewayMessage_Heartbeat
	//	*GatewayMessage_Enrollment
	Payload       isGatewayMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayMessage) Reset() {
	*x = GatewayMessage{}
	mi := &file_axioma_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayMessage) ProtoMessage() {}

func (x *GatewayMessage) ProtoReflect() protoreflect.Message {
	mi := &file_axioma_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayMessage.ProtoReflect.Descriptor instead.
func (*GatewayMessage) Descriptor() ([]byte, []int) {
	return file_axioma_proto_rawDescGZIP(), []int{13}
}

func (x *GatewayMessage) GetPayload() isGatewayMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *GatewayMessage) GetCommand() *DeviceCommand {
	if x != nil {
		if x, ok := x.Payload.(*GatewayMessage_Command); ok {
			return x.Command
		}
	}
	return nil
}

func (x *GatewayMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*GatewayMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *GatewayMessage) GetEnrollment() *DeviceEnrollment {
	if x != nil {
		if x, ok := x.Payload.(*GatewayMessage_Enrollment); ok {
			return x.Enrollment
		}
	}
	return nil
}

type isGatewayMessage_Payload interface {
	isGatewayMessage_Payload()
}

type GatewayMessage_Command struct {
	Command *DeviceCommand `protobuf:"bytes,1,opt,name=command,proto3,oneof"`
}

type GatewayMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type GatewayMessage_Enrollment struct {
	Enrollment *DeviceEnrollment `protobuf:"bytes,3,opt,name=enrollment,proto3,oneof"`
}

func (*GatewayMessage_Command) isGatewayMessage_Payload() {}

func (*GatewayMessage_Heartbeat) isGatewayMessage_Payload() {}

func (*GatewayMessage_Enrollment) isGatewayMessage_Payload() {}

type DeviceEnrollment struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Claimed     bool                   `protobuf:"varint,1,opt,name=claimed,proto3" json:"claimed,omitempty"`
	CodeExpired bool                   `protobuf:"varint,2,opt,name=code_expired,json=codeExpired,proto3" json:"code_expired,omitempty"`
	// Returned once after enrolment, or pushed to an online device during rotation.
	Credential string `protobuf:"bytes,3,opt,name=credential,proto3" json:"credential,omitempty"`
	AuthValid  bool   `protobuf:"varint,4,opt,name=auth_valid,json=authValid,proto3" json:"auth_valid,omitempty"`
	// Short code the employee types into the portal to claim this machine as
	// theirs. Sent once, on the message that completes enrolment; empty on every
	// later message. Enrolment alone leaves the device unowned, so without this
	// the device never appears in the employee's own list.
	ClaimCode     string `protobuf:"bytes,5,opt,name=claim_code,json=claimCode,proto3" json:"claim_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceEnrollment) Reset() {
	*x = DeviceEnrollment{}
	mi := &file_axioma_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceEnrollment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceEnrollment) ProtoMessage() {}

func (x *DeviceEnrollment) ProtoReflect() protoreflect.Message {
	mi := &file_axioma_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceEnrollment.ProtoReflect.Descriptor instead.
func (*DeviceEnrollment) Descriptor() ([]byte, []int) {
	return file_axioma_proto_rawDescGZIP(), []int{14}
}

func (x *DeviceEnrollment) GetClaimed() bool {
	if x != nil {
		return x.Claimed
	}
	return false
}

func (x *DeviceEnrollment) GetCodeExpired() bool {
	if x != nil {
		return x.CodeExpired
	}
	return false
}

func (x *DeviceEnrollment) GetCredential() string {
	if x != nil {
		return x.Credential
	}
	return ""
}

func (x *DeviceEnrollment) GetAuthValid() bool {
	if x != nil {
		return x.AuthValid
	}
	return false
}

func (x *DeviceEnrollment) GetClaimCode() string {
	if x != nil {
		return x.ClaimCode
	}
	return ""
}

type DeviceHello struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUID minted on first run and persisted to the user profile. Survives
	// restarts and network roaming; dies with the profile, which is the right
	// lifetime for "this person's laptop".
	DeviceId     string `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Hostname     string `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Username     string `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Platform     string `protobuf:"bytes,4,opt,name=platform,proto3" json:"platform,omitempty"`
	Release      string `protobuf:"bytes,5,opt,name=release,proto3" json:"release,omitempty"`
	AgentVersion string `protobuf:"bytes,6,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	// Last sequence the device processed. The gateway replays past it, because a
	// laptop that slept never got to acknowledge anything.
	LastSeenSequence uint64 `protobuf:"varint,7,opt,name=last_seen_sequence,json=lastSeenSequence,proto3" json:"last_seen_sequence,omitempty"`
	// A short-lived, single-use token is presented only for first enrolment.
	EnrolmentToken string `protobuf:"bytes,8,opt,name=enrolment_token,json=enrolmentToken,proto3" json:"enrolment_token,omitempty"`
	// Long-lived bearer credential bound to this device UUID.
	Credential    string `protobuf:"bytes,9,opt,name=credential,proto3" json:"credential,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceHello) Reset() {
	*x = DeviceHello{}
	mi := &file_axioma_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceHello) ProtoMessage() {}

func (x *DeviceHello) ProtoReflect() protoreflect.Message {
	mi := &file_axioma_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceHello.ProtoReflect.Descriptor instead.
func (*DeviceHello) Descriptor() ([]byte, []int) {
	return file_axioma_proto_rawDescGZIP(), []int{15}
}

func (x *DeviceHello) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeviceHello) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *DeviceHello) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *DeviceHello) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *DeviceHello) GetRelease() string {
	if x != nil {
		return x.Release
	}
	return ""
}

func (x *DeviceHello) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *DeviceHello) GetLastSeenSequence() uint64 {
	if x != nil {
		return x.LastSeenSequence
	}
	return 0
}

func (x *DeviceHello) GetEnrolmentToken() string {
	if x != nil {
		return x.EnrolmentToken
	}
	return ""
}

func (x *DeviceHello) GetCredential() string {
	if x != nil {
		return x.Credential
	}
	return ""
}

type DeviceCommand struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	CommandId string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Sequence  uint64                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// Tier one: a named action from a fixed set the device implements. No command
	// string ever crosses this boundary.
	Action     string            `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	Parameters map[string]string `protobuf:"bytes,4,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// The pixel fallback, for a surface with no accessibility tree. GUI
	// remediation itself is tier one shaped: the gui_* actions above drive UI
	// Automation and need nothing installed. Absent means the device cannot
	// serve this request, and it is currently absent everywhere.
	ComputerUse    bool   `protobuf:"varint,5,opt,name=computer_use,json=computerUse,proto3" json:"computer_use,omitempty"`
	Objective      string `protobuf:"bytes,6,opt,name=objective,proto3" json:"objective,omitempty"`
	TimeoutSeconds uint32 `protobuf:"varint,7,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeviceCommand) Reset() {
	*x = DeviceCommand{}
	mi := &file_axioma_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceCommand) ProtoMessage() {}

func (x *DeviceCommand) ProtoReflect() protoreflect.Message {
	mi := &file_axioma_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceCommand.ProtoReflect.Descriptor instead.
func (*DeviceCommand) Descriptor() ([]byte, []int) {
	return file_axioma_proto_rawDescGZIP(), []int{16}
}

func (x *DeviceCommand) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *DeviceCommand) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *DeviceCommand) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *DeviceCommand) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *DeviceCommand) GetComputerUse() bool {
	if x != nil {
		return x.ComputerUse
	}
	return false
}

func (x *DeviceCommand) GetObjective() string {
	if x != nil {
		return x.Objective
	}
	return ""
}

func (x *DeviceCommand) GetTimeoutSeconds() uint32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type CommandResult struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	CommandId  string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Sequence   uint64                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Ok         bool                   `protobuf:"varint,3,opt,name=ok,proto3" json:"ok,omitempty"`
	OutputJson string                 `protobuf:"bytes,4,opt,name=output_json,json=outputJson,proto3" json:"output_json,omitempty"`
	Error      string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	// Terminal status when the boolean cannot express it. A replayed sequence is
	// acknowledged without re-running the command, so the device knows only that
	// it once accepted the sequence — not whether the work succeeded. Left empty
	// for ordinary results, where the API derives the status from `ok`. Values
	// come from COMMAND_STATUSES in api/src/shared.
	Status        string `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_axioma_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_axioma_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_axioma_proto_rawDescGZIP(), []int{17}
}

func (x *CommandResult) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandResult) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *CommandResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *CommandResult) GetOutputJson() string {
	if x != nil {
		return x.OutputJson
	}
	return ""
}

func (x *CommandResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CommandResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_axioma_proto protoreflect.FileDescriptor

const file_axioma_proto_rawDesc = "" +
	"\n" +
	"\faxioma.proto\x12\taxioma.v1\"\xaf\x02\n" +
	"\fAgentMessage\x12-\n" +
	"\x05hello\x18\x01 \x01(\v2\x15.axioma.v1.AgentHelloH\x00R\x05hello\x125\n" +
	"\n" +
	"run_update\x18\x02 \x01(\v2\x14.axioma.v1.RunUpdateH\x00R\trunUpdate\x12;\n" +
	"\ftool_request\x18\x03 \x01(\v2\x16.axioma.v1.ToolRequestH\x00R\vtoolRequest\x124\n" +
	"\theartbeat\x18\x04 \x01(\v2\x14.axioma.v1.HeartbeatH\x00R\theartbeat\x12;\n" +
	"\frun_accepted\x18\x05 \x01(\v2\x16.axioma.v1.RunAcceptedH\x00R\vrunAcceptedB\t\n" +
	"\apayload\"$\n" +
	"\vRunAccepted\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\"\xaf\x02\n" +
	"\n" +
	"ApiMessage\x122\n" +
	"\tstart_run\x18\x01 \x01(\v2\x13.axioma.v1.StartRunH\x00R\bstartRun\x128\n" +
	"\vtool_result\x18\x02 \x01(\v2\x15.axioma.v1.ToolResultH\x00R\n" +
	"toolResult\x125\n" +
	"\n" +
	"cancel_run\x18\x03 \x01(\v2\x14.axioma.v1.CancelRunH\x00R\tcancelRun\x124\n" +
	"\theartbeat\x18\x04 \x01(\v2\x14.axioma.v1.HeartbeatH\x00R\theartbeat\x12;\n" +
	"\fterminal_ack\x18\x05 \x01(\v2\x16.axioma.v1.TerminalAckH\x00R\vterminalAckB\t\n" +
	"\apayload\">\n" +
	"\vTerminalAck\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x18\n" +
	"\aordinal\x18\x02 \x01(\rR\aordinal\"\xb3\x01\n" +
	"\n" +
	"AgentHello\x12#\n" +
	"\ragent_version\x18\x01 \x01(\tR\fagentVersion\x12\x1f\n" +
	"\vmodel_label\x18\x02 \x01(\tR\n" +
	"modelLabel\x12\"\n" +
	"\fcapabilities\x18\x03 \x03(\tR\fcapabilities\x12\x1b\n" +
	"\tworker_id\x18\x04 \x01(\tR\bworkerId\x12\x1e\n" +
	"\n" +
	"credential\x18\x05 \x01(\tR\n" +
	"credential\"\xa1\x04\n" +
	"\bStartRun\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x1b\n" +
	"\tticket_id\x18\x02 \x01(\tR\bticketId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12\x1f\n" +
	"\vreporter_id\x18\x05 \x01(\tR\n" +
	"reporterId\x12\x1b\n" +
	"\tdevice_id\x18\x06 \x01(\tR\bdeviceId\x12!\n" +
	"\fcontext_json\x18\a \x01(\tR\vcontextJson\x12\x1f\n" +
	"\vrecord_type\x18\b \x01(\tR\n" +
	"recordType\x12\x16\n" +
	"\x06impact\x18\t \x01(\tR\x06impact\x12\x18\n" +
	"\aurgency\x18\n" +
	" \x01(\tR\aurgency\x12\x1a\n" +
	"\bpriority\x18\v \x01(\tR\bpriority\x12\x16\n" +
	"\x06origin\x18\f \x01(\tR\x06origin\x12 \n" +
	"\venvironment\x18\r \x01(\tR\venvironment\x12#\n" +
	"\rreporter_name\x18\x0e \x01(\tR\freporterName\x12,\n" +
	"\x12reporter_job_title\x18\x0f \x01(\tR\x10reporterJobTitle\x12/\n" +
	"\x13reporter_department\x18\x10 \x01(\tR\x12reporterDepartment\x12)\n" +
	"\x10reporter_manager\x18\x11 \x01(\tR\x0freporterManager\":\n" +
	"\tCancelRun\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\xa8\x05\n" +
	"\tRunUpdate\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x18\n" +
	"\aordinal\x18\x02 \x01(\rR\aordinal\x12-\n" +
	"\x04kind\x18\x03 \x01(\x0e2\x19.axioma.v1.RunUpdate.KindR\x04kind\x12\x1c\n" +
	"\treasoning\x18\x04 \x01(\tR\treasoning\x12\x1b\n" +
	"\ttool_name\x18\x05 \x01(\tR\btoolName\x12&\n" +
	"\x0ftool_input_json\x18\x06 \x01(\tR\rtoolInputJson\x12(\n" +
	"\x10tool_output_json\x18\a \x01(\tR\x0etoolOutputJson\x12\x14\n" +
	"\x05error\x18\b \x01(\tR\x05error\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x12\x18\n" +
	"\aoutcome\x18\n" +
	" \x01(\tR\aoutcome\x12\x1a\n" +
	"\bevidence\x18\v \x01(\tR\bevidence\x12#\n" +
	"\rprompt_tokens\x18\f \x01(\rR\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\r \x01(\rR\x10completionTokens\x12\x14\n" +
	"\x05model\x18\x0e \x01(\tR\x05model\x12'\n" +
	"\x0fresolution_code\x18\x0f \x01(\tR\x0eresolutionCode\x12\x16\n" +
	"\x06notice\x18\x10 \x01(\tR\x06notice\x12#\n" +
	"\revidence_tone\x18\x11 \x01(\tR\fevidenceTone\"|\n" +
	"\x04Kind\x12\x14\n" +
	"\x10KIND_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"KIND_THINK\x10\x01\x12\x12\n" +
	"\x0eKIND_TOOL_CALL\x10\x02\x12\x14\n" +
	"\x10KIND_OBSERVATION\x10\x03\x12\x11\n" +
	"\rKIND_DECISION\x10\x04\x12\x11\n" +
	"\rKIND_TERMINAL\x10\x05\"\xa9\x01\n" +
	"\vToolRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x17\n" +
	"\acall_id\x18\x02 \x01(\tR\x06callId\x12\x1b\n" +
	"\ttool_name\x18\x03 \x01(\tR\btoolName\x12\x1d\n" +
	"\n" +
	"input_json\x18\x04 \x01(\tR\tinputJson\x12.\n" +
	"\x13source_step_ordinal\x18\x05 \x01(\rR\x11sourceStepOrdinal\"\x83\x01\n" +
	"\n" +
	"ToolResult\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x17\n" +
	"\acall_id\x18\x02 \x01(\tR\x06callId\x12\x0e\n" +
	"\x02ok\x18\x03 \x01(\bR\x02ok\x12\x1f\n" +
	"\voutput_json\x18\x04 \x01(\tR\n" +
	"outputJson\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"$\n" +
	"\tHeartbeat\x12\x17\n" +
	"\aunix_ms\x18\x01 \x01(\x03R\x06unixMs\"\xf0\x01\n" +
	"\rDeviceMessage\x12.\n" +
	"\x05hello\x18\x01 \x01(\v2\x16.axioma.v1.DeviceHelloH\x00R\x05hello\x122\n" +
	"\x06result\x18\x02 \x01(\v2\x18.axioma.v1.CommandResultH\x00R\x06result\x124\n" +
	"\theartbeat\x18\x03 \x01(\v2\x14.axioma.v1.HeartbeatH\x00R\theartbeat\x12:\n" +
	"\tinventory\x18\x04 \x01(\v2\x1a.axioma.v1.InventoryReportH\x00R\tinventoryB\t\n" +
	"\apayload\"\x81\x01\n" +
	"\x0fInventoryReport\x12\x1b\n" +
	"\treport_id\x18\x01 \x01(\tR\breportId\x12*\n" +
	"\x11collected_unix_ms\x18\x02 \x01(\x03R\x0fcollectedUnixMs\x12%\n" +
	"\x0einventory_json\x18\x03 \x01(\tR\rinventoryJson\"\xc6\x01\n" +
	"\x0eGatewayMessage\x124\n" +
	"\acommand\x18\x01 \x01(\v2\x18.axioma.v1.DeviceCommandH\x00R\acommand\x124\n" +
	"\theartbeat\x18\x02 \x01(\v2\x14.axioma.v1.HeartbeatH\x00R\theartbeat\x12=\n" +
	"\n" +
	"enrollment\x18\x03 \x01(\v2\x1b.axioma.v1.DeviceEnrollmentH\x00R\n" +
	"enrollmentB\t\n" +
	"\apayload\"\xad\x01\n" +
	"\x10DeviceEnrollment\x12\x18\n" +
	"\aclaimed\x18\x01 \x01(\bR\aclaimed\x12!\n" +
	"\fcode_expired\x18\x02 \x01(\bR\vcodeExpired\x12\x1e\n" +
	"\n" +
	"credential\x18\x03 \x01(\tR\n" +
	"credential\x12\x1d\n" +
	"\n" +
	"auth_valid\x18\x04 \x01(\bR\tauthValid\x12\x1d\n" +
	"\n" +
	"claim_code\x18\x05 \x01(\tR\tclaimCode\"\xb4\x02\n" +
	"\vDeviceHello\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1a\n" +
	"\bplatform\x18\x04 \x01(\tR\bplatform\x12\x18\n" +
	"\arelease\x18\x05 \x01(\tR\arelease\x12#\n" +
	"\ragent_version\x18\x06 \x01(\tR\fagentVersion\x12,\n" +
	"\x12last_seen_sequence\x18\a \x01(\x04R\x10lastSeenSequence\x12'\n" +
	"\x0fenrolment_token\x18\b \x01(\tR\x0eenrolmentToken\x12\x1e\n" +
	"\n" +
	"credential\x18\t \x01(\tR\n" +
	"credential\"\xd5\x02\n" +
	"\rDeviceCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12H\n" +
	"\n" +
	"parameters\x18\x04 \x03(\v2(.axioma.v1.DeviceCommand.ParametersEntryR\n" +
	"parameters\x12!\n" +
	"\fcomputer_use\x18\x05 \x01(\bR\vcomputerUse\x12\x1c\n" +
	"\tobjective\x18\x06 \x01(\tR\tobjective\x12'\n" +
	"\x0ftimeout_seconds\x18\a \x01(\rR\x0etimeoutSeconds\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa9\x01\n" +
	"\rCommandResult\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\x12\x0e\n" +
	"\x02ok\x18\x03 \x01(\bR\x02ok\x12\x1f\n" +
	"\voutput_json\x18\x04 \x01(\tR\n" +
	"outputJson\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status*\xcc\x05\n" +
	"\fDeviceAction\x12\x1d\n" +
	"\x19DEVICE_ACTION_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17DEVICE_ACTION_FLUSH_DNS\x10\x01\x12\"\n" +
	"\x1eDEVICE_ACTION_RENEW_DHCP_LEASE\x10\x02\x12&\n" +
	"\"DEVICE_ACTION_CLEAR_PROXY_OVERRIDE\x10\x03\x12(\n" +
	"$DEVICE_ACTION_RESET_CREDENTIAL_CACHE\x10\x04\x12&\n" +
	"\"DEVICE_ACTION_RESTART_USER_PROCESS\x10\x05\x12\x1f\n" +
	"\x1bDEVICE_ACTION_DISABLE_PROXY\x10\x06\x12+\n" +
	"'DEVICE_ACTION_REFRESH_CERTIFICATE_STORE\x10\a\x12\"\n" +
	"\x1eDEVICE_ACTION_CLEAR_TEMP_FILES\x10\b\x12%\n" +
	"!DEVICE_ACTION_CLEAR_OUTLOOK_CACHE\x10\t\x12#\n" +
	"\x1fDEVICE_ACTION_CLEAR_TEAMS_CACHE\x10\n" +
	"\x12\"\n" +
	"\x1eDEVICE_ACTION_CLEAR_ICON_CACHE\x10\v\x12#\n" +
	"\x1fDEVICE_ACTION_CLEAR_PRINT_QUEUE\x10\f\x12$\n" +
	" DEVICE_ACTION_GUI_INVOKE_CONTROL\x10\r\x12'\n" +
	"#DEVICE_ACTION_GUI_SET_CONTROL_VALUE\x10\x0e\x12$\n" +
	" DEVICE_ACTION_GUI_TOGGLE_CONTROL\x10\x0f\x12!\n" +
	"\x1dDEVICE_ACTION_GUI_SELECT_ITEM\x10\x10\x12$\n" +
	" DEVICE_ACTION_GUI_EXPAND_CONTROL\x10\x11\x12\x1d\n" +
	"\x19DEVICE_ACTION_RUN_COMMAND\x10\x12*\xd8\x02\n" +
	"\vDeviceFacet\x12\x1c\n" +
	"\x18DEVICE_FACET_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15DEVICE_FACET_RESOLVER\x10\x01\x12\x19\n" +
	"\x15DEVICE_FACET_ADAPTERS\x10\x02\x12\x1d\n" +
	"\x19DEVICE_FACET_REACHABILITY\x10\x03\x12\x16\n" +
	"\x12DEVICE_FACET_PROXY\x10\x04\x12\x19\n" +
	"\x15DEVICE_FACET_IDENTITY\x10\x05\x12\x1a\n" +
	"\x16DEVICE_FACET_PROCESSES\x10\x06\x12\x1d\n" +
	"\x19DEVICE_FACET_CERTIFICATES\x10\a\x12\x18\n" +
	"\x14DEVICE_FACET_STORAGE\x10\b\x12\x1a\n" +
	"\x16DEVICE_FACET_APP_CACHE\x10\t\x12\x19\n" +
	"\x15DEVICE_FACET_PRINTING\x10\n" +
	"\x12\x17\n" +
	"\x13DEVICE_FACET_SCREEN\x10\v2M\n" +
	"\fAgentChannel\x12=\n" +
	"\aConnect\x12\x17.axioma.v1.AgentMessage\x1a\x15.axioma.v1.ApiMessage(\x010\x012S\n" +
	"\rDeviceChannel\x12B\n" +
	"\aConnect\x12\x18.axioma.v1.DeviceMessage\x1a\x19.axioma.v1.GatewayMessage(\x010\x01B&Z$github.com/axioma/cli/internal/pb;pbb\x06proto3"

var (
	file_axioma_proto_rawDescOnce sync.Once
	file_axioma_proto_rawDescData []byte
)

func file_axioma_proto_rawDescGZIP() []byte {
	file_axioma_proto_rawDescOnce.Do(func() {
		file_axioma_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_axioma_proto_rawDesc), len(file_axioma_proto_rawDesc)))
	})
	return file_axioma_proto_rawDescData
}

var file_axioma_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_axioma_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_axioma_proto_goTypes = []any{
	(DeviceAction)(0),        // 0: axioma.v1.DeviceAction
	(DeviceFacet)(0),         // 1: axioma.v1.DeviceFacet
	(RunUpdate_Kind)(0),      // 2: axioma.v1.RunUpdate.Kind
	(*AgentMessage)(nil),     // 3: axioma.v1.AgentMessage
	(*RunAccepted)(nil),      // 4: axioma.v1.RunAccepted
	(*ApiMessage)(nil),       // 5: axioma.v1.ApiMessage
	(*TerminalAck)(nil),      // 6: axioma.v1.TerminalAck
	(*AgentHello)(nil),       // 7: axioma.v1.AgentHello
	(*StartRun)(nil),         // 8: axioma.v1.StartRun
	(*CancelRun)(nil),        // 9: axioma.v1.CancelRun
	(*RunUpdate)(nil),        // 10: axioma.v1.RunUpdate
	(*ToolRequest)(nil),      // 11: axioma.v1.ToolRequest
	(*ToolResult)(nil),       // 12: axioma.v1.ToolResult
	(*Heartbeat)(nil),        // 13: axioma.v1.Heartbeat
	(*DeviceMessage)(nil),    // 14: axioma.v1.DeviceMessage
	(*InventoryReport)(nil),  // 15: axioma.v1.InventoryReport
	(*GatewayMessage)(nil),   // 16: axioma.v1.GatewayMessage
	(*DeviceEnrollment)(nil), // 17: axioma.v1.DeviceEnrollment
	(*DeviceHello)(nil),      // 18: axioma.v1.DeviceHello
	(*DeviceCommand)(nil),    // 19: axioma.v1.DeviceCommand
	(*CommandResult)(nil),    // 20: axioma.v1.CommandResult
	nil,                      // 21: axioma.v1.DeviceCommand.ParametersEntry
}
var file_axioma_proto_depIdxs = []int32{
	7,  // 0: axioma.v1.AgentMessage.hello:type_name -> axioma.v1.AgentHello
	10, // 1: axioma.v1.AgentMessage.run_update:type_name -> axioma.v1.RunUpdate
	11, // 2: axioma.v1.AgentMessage.tool_request:type_name -> axioma.v1.ToolRequest
	13, // 3: axioma.v1.AgentMessage.heartbeat:type_name -> axioma.v1.Heartbeat
	4,  // 4: axioma.v1.AgentMessage.run_accepted:type_name -> axioma.v1.RunAccepted
	8,  // 5: axioma.v1.ApiMessage.start_run:type_name -> axioma.v1.StartRun
	12, // 6: axioma.v1.ApiMessage.tool_result:type_name -> axioma.v1.ToolResult
	9,  // 7: axioma.v1.ApiMessage.cancel_run:type_name -> axioma.v1.CancelRun
	13, // 8: axioma.v1.ApiMessage.heartbeat:type_name -> axioma.v1.Heartbeat
	6,  // 9: axioma.v1.ApiMessage.terminal_ack:type_name -> axioma.v1.TerminalAck
	2,  // 10: axioma.v1.RunUpdate.kind:type_name -> axioma.v1.RunUpdate.Kind
	18, // 11: axioma.v1.DeviceMessage.hello:type_name -> axioma.v1.DeviceHello
	20, // 12: axioma.v1.DeviceMessage.result:type_name -> axioma.v1.CommandResult
	13, // 13: axioma.v1.DeviceMessage.heartbeat:type_name -> axioma.v1.Heartbeat
	15, // 14: axioma.v1.DeviceMessage.inventory:type_name -> axioma.v1.InventoryReport
	19, // 15: axioma.v1.GatewayMessage.command:type_name -> axioma.v1.DeviceCommand
	13, // 16: axioma.v1.GatewayMessage.heartbeat:type_name -> axioma.v1.Heartbeat
	17, // 17: axioma.v1.GatewayMessage.enrollment:type_name -> axioma.v1.DeviceEnrollment
	21, // 18: axioma.v1.DeviceCommand.parameters:type_name -> axioma.v1.DeviceCommand.ParametersEntry
	3,  // 19: axioma.v1.AgentChannel.Connect:input_type -> axioma.v1.AgentMessage
	14, // 20: axioma.v1.DeviceChannel.Connect:input_type -> axioma.v1.DeviceMessage
	5,  // 21: axioma.v1.AgentChannel.Connect:output_type -> axioma.v1.ApiMessage
	16, // 22: axioma.v1.DeviceChannel.Connect:output_type -> axioma.v1.GatewayMessage
	21, // [21:23] is the sub-list for method output_type
	19, // [19:21] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_axioma_proto_init() }
func file_axioma_proto_init() {
	if File_axioma_proto != nil {
		return
	}
	file_axioma_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentMessage_Hello)(nil),
		(*AgentMessage_RunUpdate)(nil),
		(*AgentMessage_ToolRequest)(nil),
		(*AgentMessage_Heartbeat)(nil),
		(*AgentMessage_RunAccepted)(nil),
	}
	file_axioma_proto_msgTypes[2].OneofWrappers = []any{
		(*ApiMessage_StartRun)(nil),
		(*ApiMessage_ToolResult)(nil),
		(*ApiMessage_CancelRun)(nil),
		(*ApiMessage_Heartbeat)(nil),
		(*ApiMessage_TerminalAck)(nil),
	}
	file_axioma_proto_msgTypes[11].OneofWrappers = []any{
		(*DeviceMessage_Hello)(nil),
		(*DeviceMessage_Result)(nil),
		(*DeviceMessage_Heartbeat)(nil),
		(*DeviceMessage_Inventory)(nil),
	}
	file_axioma_proto_msgTypes[13].OneofWrappers = []any{
		(*GatewayMessage_Command)(nil),
		(*GatewayMessage_Heartbeat)(nil),
		(*GatewayMessage_Enrollment)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_axioma_proto_rawDesc), len(file_axioma_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_axioma_proto_goTypes,
		DependencyIndexes: file_axioma_proto_depIdxs,
		EnumInfos:         file_axioma_proto_enumTypes,
		MessageInfos:      file_axioma_proto_msgTypes,
	}.Build()
	File_axioma_proto = out.File
	file_axioma_proto_goTypes = nil
	file_axioma_proto_depIdxs = nil
}
