// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.35.1
// source: axioma.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentChannel_Connect_FullMethodName = "/axioma.v1.AgentChannel/Connect"
)

// AgentChannelClient is the client API for AgentChannel service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentChannelClient interface {
	// The agent is the client. It dials the API and holds the stream open.
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMessage, ApiMessage], error)
}

type agentChannelClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentChannelClient(cc grpc.ClientConnInterface) AgentChannelClient {
	return &agentChannelClient{cc}
}

func (c *agentChannelClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMessage, ApiMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentChannel_ServiceDesc.Streams[0], AgentChannel_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentMessage, ApiMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentChannel_ConnectClient = grpc.BidiStreamingClient[AgentMessage, ApiMessage]

// AgentChannelServer is the server API for AgentChannel service.
// All implementations must embed UnimplementedAgentChannelServer
// for forward compatibility.
type AgentChannelServer interface {
	// The agent is the client. It dials the API and holds the stream open.
	Connect(grpc.BidiStreamingServer[AgentMessage, ApiMessage]) error
	mustEmbedUnimplementedAgentChannelServer()
}

// UnimplementedAgentChannelServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentChannelServer struct{}

func (UnimplementedAgentChannelServer) Connect(grpc.BidiStreamingServer[AgentMessage, ApiMessage]) error {
	return status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedAgentChannelServer) mustEmbedUnimplementedAgentChannelServer() {}
func (UnimplementedAgentChannelServer) testEmbeddedByValue()                      {}

// UnsafeAgentChannelServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentChannelServer will
// result in compilation errors.
type UnsafeAgentChannelServer interface {
	mustEmbedUnimplementedAgentChannelServer()
}

func RegisterAgentChannelServer(s grpc.ServiceRegistrar, srv AgentChannelServer) {
	// If the following call pancis, it indicates UnimplementedAgentChannelServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentChannel_ServiceDesc, srv)
}

func _AgentChannel_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentChannelServer).Connect(&grpc.GenericServerStream[AgentMessage, ApiMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentChannel_ConnectServer = grpc.BidiStreamingServer[AgentMessage, ApiMessage]

// AgentChannel_ServiceDesc is the grpc.ServiceDesc for AgentChannel service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentChannel_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "axioma.v1.AgentChannel",
	HandlerType: (*AgentChannelServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _AgentChannel_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "axioma.proto",
}

const (
	DeviceChannel_Connect_FullMethodName = "/axioma.v1.DeviceChannel/Connect"
)

// DeviceChannelClient is the client API for DeviceChannel service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeviceChannelClient interface {
	// The device is the client. Outbound only: it works through NAT, on home
	// networks, and behind corporate proxies without a firewall change.
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DeviceMessage, GatewayMessage], error)
}

type deviceChannelClient struct {
	cc grpc.ClientConnInterface
}

func NewDeviceChannelClient(cc grpc.ClientConnInterface) DeviceChannelClient {
	return &deviceChannelClient{cc}
}

func (c *deviceChannelClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DeviceMessage, GatewayMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DeviceChannel_ServiceDesc.Streams[0], DeviceChannel_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DeviceMessage, GatewayMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DeviceChannel_ConnectClient = grpc.BidiStreamingClient[DeviceMessage, GatewayMessage]

// DeviceChannelServer is the server API for DeviceChannel service.
// All implementations must embed UnimplementedDeviceChannelServer
// for forward compatibility.
type DeviceChannelServer interface {
	// The device is the client. Outbound only: it works through NAT, on home
	// networks, and behind corporate proxies without a firewall change.
	Connect(grpc.BidiStreamingServer[DeviceMessage, GatewayMessage]) error
	mustEmbedUnimplementedDeviceChannelServer()
}

// UnimplementedDeviceChannelServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeviceChannelServer struct{}

func (UnimplementedDeviceChannelServer) Connect(grpc.BidiStreamingServer[DeviceMessage, GatewayMessage]) error {
	return status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedDeviceChannelServer) mustEmbedUnimplementedDeviceChannelServer() {}
func (UnimplementedDeviceChannelServer) testEmbeddedByValue()                       {}

// UnsafeDeviceChannelServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeviceChannelServer will
// result in compilation errors.
type UnsafeDeviceChannelServer interface {
	mustEmbedUnimplementedDeviceChannelServer()
}

func RegisterDeviceChannelServer(s grpc.ServiceRegistrar, srv DeviceChannelServer) {
	// If the following call pancis, it indicates UnimplementedDeviceChannelServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DeviceChannel_ServiceDesc, srv)
}

func _DeviceChannel_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DeviceChannelServer).Connect(&grpc.GenericServerStream[DeviceMessage, GatewayMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DeviceChannel_ConnectServer = grpc.BidiStreamingServer[DeviceMessage, GatewayMessage]

// DeviceChannel_ServiceDesc is the grpc.ServiceDesc for DeviceChannel service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeviceChannel_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "axioma.v1.DeviceChannel",
	HandlerType: (*DeviceChannelServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _DeviceChannel_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "axioma.proto",
}
