ALTER TABLE "tickets" ADD CONSTRAINT "tickets_status_ticket_statuses_fk" FOREIGN KEY ("status") REFERENCES "ticket_statuses"("key") NOT VALID;
ALTER TABLE "tickets" VALIDATE CONSTRAINT "tickets_status_ticket_statuses_fk";
ALTER TABLE "tickets" ADD CONSTRAINT "tickets_merged_into_fk" FOREIGN KEY ("merged_into_id") REFERENCES "tickets"("id") ON DELETE SET NULL NOT VALID;
ALTER TABLE "tickets" VALIDATE CONSTRAINT "tickets_merged_into_fk";
ALTER TABLE "tickets" ADD CONSTRAINT "tickets_pending_reason_fk" FOREIGN KEY ("pending_reason_id") REFERENCES "pending_reasons"("id") ON DELETE SET NULL NOT VALID;
ALTER TABLE "tickets" VALIDATE CONSTRAINT "tickets_pending_reason_fk";
ALTER TABLE "tickets" ADD CONSTRAINT "tickets_team_fk" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE SET NULL NOT VALID;
ALTER TABLE "tickets" VALIDATE CONSTRAINT "tickets_team_fk";
ALTER TABLE "olas" ADD CONSTRAINT "olas_calendar_fk" FOREIGN KEY ("calendar_id") REFERENCES "calendars"("id") NOT VALID;
ALTER TABLE "olas" VALIDATE CONSTRAINT "olas_calendar_fk";
--> statement-breakpoint
ALTER TABLE "calendar_hours" ADD CONSTRAINT "calendar_hours_weekday_check" CHECK ("weekday" BETWEEN 0 AND 6);
ALTER TABLE "calendar_hours" ADD CONSTRAINT "calendar_hours_range_check" CHECK ("start_time" < "end_time");
ALTER TABLE "pending_reasons" ADD CONSTRAINT "pending_reasons_frequency_positive" CHECK ("followup_frequency_minutes" > 0);
ALTER TABLE "pending_reasons" ADD CONSTRAINT "pending_reasons_followups_positive" CHECK ("followups_before_resolution" > 0);
ALTER TABLE "ticket_csat_responses" ADD CONSTRAINT "ticket_csat_response_complete" CHECK (("rating" IS NULL AND "responded_at" IS NULL) OR ("rating" IS NOT NULL AND "responded_at" IS NOT NULL));
ALTER TABLE "slas" ADD CONSTRAINT "slas_tto_positive" CHECK ("tto_working_minutes" > 0);
ALTER TABLE "slas" ADD CONSTRAINT "slas_ttr_positive" CHECK ("ttr_working_minutes" > 0);
ALTER TABLE "olas" ADD CONSTRAINT "olas_tto_positive" CHECK ("tto_working_minutes" > 0);
ALTER TABLE "olas" ADD CONSTRAINT "olas_ttr_positive" CHECK ("ttr_working_minutes" > 0);
ALTER TABLE "ticket_stopwatches" ADD CONSTRAINT "ticket_stopwatches_accumulated_nonnegative" CHECK ("accumulated_ms" >= 0);
ALTER TABLE "ticket_stopwatches" ADD CONSTRAINT "ticket_stopwatches_pending_nonnegative" CHECK ("pending_ms" >= 0);
ALTER TABLE "sla_notification_rules" ADD CONSTRAINT "sla_notification_rules_threshold_range" CHECK ("threshold_percent" > 0 AND "threshold_percent" <= 100);
ALTER TABLE "sla_notification_rules" ADD CONSTRAINT "sla_notification_rules_recipient_shape" CHECK (("recipient_type" = 'assignee' AND "recipient" IS NULL) OR ("recipient_type" <> 'assignee' AND "recipient" IS NOT NULL));
--> statement-breakpoint
CREATE INDEX "ticket_statuses_order_idx" ON "ticket_statuses" ("is_active", "display_order");
CREATE INDEX "calendars_default_idx" ON "calendars" ("is_default");
CREATE INDEX "calendar_hours_calendar_idx" ON "calendar_hours" ("calendar_id", "weekday");
CREATE INDEX "pending_followups_ticket_idx" ON "pending_followups" ("ticket_id", "created_at");
CREATE INDEX "ticket_links_target_idx" ON "ticket_links" ("target_ticket_id");
CREATE INDEX "ticket_merges_source_idx" ON "ticket_merges" ("source_ticket_id", "merged_at");
CREATE INDEX "ticket_merges_target_idx" ON "ticket_merges" ("target_ticket_id", "merged_at");
CREATE INDEX "ticket_audit_ticket_idx" ON "ticket_audit" ("ticket_id", "created_at");
CREATE INDEX "ticket_time_entries_ticket_idx" ON "ticket_time_entries" ("ticket_id", "created_at");
CREATE INDEX "ticket_number_history_ticket_idx" ON "ticket_number_history" ("ticket_id", "created_at");
CREATE INDEX "ticket_presence_expiry_idx" ON "ticket_presence" ("ticket_id", "expires_at");
CREATE INDEX "slas_priority_idx" ON "slas" ("priority");
CREATE INDEX "olas_priority_idx" ON "olas" ("priority");
CREATE INDEX "ticket_stopwatches_running_idx" ON "ticket_stopwatches" ("running", "started_at");
CREATE INDEX "sla_notification_rules_policy_idx" ON "sla_notification_rules" ("policy_type", "policy_id");
CREATE INDEX "sla_escalation_events_ticket_idx" ON "sla_escalation_events" ("ticket_id", "created_at");
