CREATE INDEX IF NOT EXISTS approvals_requester_id_idx ON approvals (requester_id);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS approvals_submission_id_idx ON approvals (submission_id);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS asset_checkout_log_custodian_id_idx ON asset_checkout_log (custodian_id);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS asset_history_actor_id_idx ON asset_history (actor_id);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS change_cab_members_user_id_idx ON change_cab_members (user_id);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS changes_approver_id_idx ON changes (approver_id);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS changes_assigned_to_id_idx ON changes (assigned_to_id);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS changes_created_by_id_idx ON changes (created_by_id);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS changes_requester_id_idx ON changes (requester_id);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS changes_source_run_id_idx ON changes (source_run_id);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS changes_source_step_id_idx ON changes (source_step_id);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS change_ticket_links_ticket_id_idx ON change_ticket_links (ticket_id);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS change_transitions_change_id_idx ON change_transitions (change_id);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS change_transitions_run_id_idx ON change_transitions (run_id);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS change_transitions_step_id_idx ON change_transitions (step_id);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS cmdb_classes_parent_class_id_idx ON cmdb_classes (parent_class_id);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS cmdb_object_properties_property_id_idx ON cmdb_object_properties (property_id);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS cmdb_object_relationships_property_id_idx ON cmdb_object_relationships (property_id);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS cmdb_object_relationships_type_id_idx ON cmdb_object_relationships (type_id);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS contract_coverage_windows_sla_id_idx ON contract_coverage_windows (sla_id);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS directory_identities_user_id_idx ON directory_identities (user_id);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS email_template_rules_template_id_idx ON email_template_rules (template_id);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS form_submissions_form_id_idx ON form_submissions (form_id);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS form_submissions_submitter_id_idx ON form_submissions (submitter_id);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS knowledge_articles_author_id_idx ON knowledge_articles (author_id);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS knowledge_articles_folder_id_idx ON knowledge_articles (folder_id);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS knowledge_article_tags_tag_id_idx ON knowledge_article_tags (tag_id);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS knowledge_article_versions_author_id_idx ON knowledge_article_versions (author_id);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS knowledge_gap_clusters_article_id_idx ON knowledge_gap_clusters (article_id);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS knowledge_gap_tickets_ticket_id_idx ON knowledge_gap_tickets (ticket_id);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS mailbox_activity_log_inbound_email_id_idx ON mailbox_activity_log (inbound_email_id);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS mailbox_activity_log_ticket_id_idx ON mailbox_activity_log (ticket_id);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS messaging_channels_default_origin_id_idx ON messaging_channels (default_origin_id);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS notifications_actor_id_idx ON notifications (actor_id);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS olas_calendar_id_idx ON olas (calendar_id);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS pending_followups_reason_id_idx ON pending_followups (reason_id);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS problems_assignee_id_idx ON problems (assignee_id);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS problems_service_id_idx ON problems (service_id);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS problems_status_idx ON problems (status);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS recurring_tickets_source_ticket_id_idx ON recurring_tickets (source_ticket_id);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS role_grants_actor_id_idx ON role_grants (actor_id);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS service_subcategories_approver_override_id_idx ON service_subcategories (approver_override_id);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS service_subcategories_form_id_idx ON service_subcategories (form_id);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS sla_escalation_events_rule_id_idx ON sla_escalation_events (rule_id);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS sla_escalation_events_stopwatch_id_idx ON sla_escalation_events (stopwatch_id);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS slas_calendar_id_idx ON slas (calendar_id);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS sso_identities_provider_id_idx ON sso_identities (provider_id);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS status_incidents_impact_level_idx ON status_incidents (impact_level);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS ticket_mail_origins_inbound_email_id_idx ON ticket_mail_origins (inbound_email_id);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS ticket_messages_author_id_idx ON ticket_messages (author_id);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS ticket_presence_user_id_idx ON ticket_presence (user_id);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS ticket_rule_firings_rule_id_idx ON ticket_rule_firings (rule_id);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS tickets_assignee_id_idx ON tickets (assignee_id);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS tickets_merged_into_id_idx ON tickets (merged_into_id);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS tickets_owner_id_idx ON tickets (owner_id);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS tickets_pending_reason_id_idx ON tickets (pending_reason_id);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS tickets_service_subcategory_id_service_id_idx ON tickets (service_subcategory_id, service_id);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS tickets_team_id_idx ON tickets (team_id);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS ticket_status_transitions_to_status_idx ON ticket_status_transitions (to_status);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS webhook_deliveries_message_format_id_idx ON webhook_deliveries (message_format_id);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS workflow_scheduled_emissions_execution_id_idx ON workflow_scheduled_emissions (execution_id);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS workflow_scheduled_emissions_workflow_id_idx ON workflow_scheduled_emissions (workflow_id);--> statement-breakpoint
