#!/usr/bin/env node
/**
 * Mirror the governed UI primitives into the apps that consume them.
 *
 * The dashboard and the portal share a large byte-identical UI layer: the
 * shadcn primitives, the global stylesheets, the theme provider, and small
 * brand/loader helpers. Copying is the same choice the api repo made for its
 * contracts: there is no registry to publish to, the consumers are checked out
 * beside this package, and a copied file that is regenerated is easier to
 * reason about than a version range that silently drifts.
 *
 * The copies are marked generated and are never edited in place. Edit the
 * source under src/ here, list the file in manifest.json for every app that
 * consumes it, and run this script. --check performs the same freshness check
 * CI uses without modifying files.
 *
 * The manifest is required, not optional: the dashboard carries primitives the
 * portal has no dependencies for (recharts, cmdk, @tanstack/react-table), so a
 * superset mirror would break the portal's type check.
 */

import { mkdir, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { isDeepStrictEqual } from "node:util";

const here = dirname(fileURLToPath(import.meta.url));
const uiRoot = resolve(here, "..");
const workspace = resolve(uiRoot, "..");

const BANNER_CODE = `// GENERATED — do not edit.
// Mirrored from axioma/ui/src by \`pnpm --dir axioma/ui mirror\`.
// Change the source in axioma/ui and re-run that command.
`;
const BANNER_CSS = `/* GENERATED — do not edit.
 * Mirrored from axioma/ui/src by \`pnpm --dir axioma/ui mirror\`.
 * Change the source in axioma/ui and re-run that command.
 */
`;
const check = process.argv.includes("--check");

async function writeOrCheck(path, expected) {
	if (check) {
		const actual = await readFile(path).catch(() => null);
		if (!actual || !isDeepStrictEqual(actual, Buffer.from(expected))) {
			throw new Error(`stale generated file: ${path}`);
		}
		return;
	}
	await writeFile(path, expected);
}

async function files(dir, prefix = "") {
	const result = [];
	for (const entry of await readdir(dir, { withFileTypes: true })) {
		const relative = prefix ? `${prefix}/${entry.name}` : entry.name;
		if (entry.isDirectory())
			result.push(...(await files(join(dir, entry.name), relative)));
		else result.push(relative);
	}
	return result.sort();
}

const manifest = JSON.parse(
	await readFile(join(uiRoot, "manifest.json"), "utf8"),
);
const sourceRoot = join(uiRoot, "src");
const sourceFiles = await files(sourceRoot);
const covered = new Set();

for (const [app, entries] of Object.entries(manifest)) {
	const known = new Set(sourceFiles);
	const seen = new Set();
	for (const relative of entries) {
		if (!known.has(relative))
			throw new Error(
				`manifest lists unknown source file for ${app}: ${relative}`,
			);
		if (seen.has(relative))
			throw new Error(`manifest lists ${relative} twice for ${app}`);
		seen.add(relative);
	}

	const targetRoot = join(workspace, app, "src");
	for (const relative of [...entries].sort()) {
		const body = await readFile(join(sourceRoot, relative));
		const banner = relative.endsWith(".css") ? BANNER_CSS : BANNER_CODE;
		const output = join(targetRoot, relative);
		await mkdir(dirname(output), { recursive: true });
		await writeOrCheck(
			output,
			`${banner}\n${body.toString("utf8").trimEnd()}\n`,
		);
	}
	// A file the manifest no longer lists — dropped from an app's slice, or
	// copied in from the other app's mirror — would otherwise sit in the target
	// unnoticed: mirroring only ever walks the source, so it is never compared
	// against anything. Identify strays by the banner they carry rather than by
	// directory ownership, because the mirrored directories also hold app-owned
	// files (lib/api-url.ts, components/header.tsx). That keeps this precise in
	// both directions: it can only ever flag, or delete, a file that declares
	// itself generated by *this* mirror — matching the provenance line rather
	// than the shared "GENERATED" header, which src/sdk carries too from the
	// api's contract mirror.
	const stray = [];
	for (const relative of await files(targetRoot).catch(() => [])) {
		if (seen.has(relative)) continue;
		if (!/\.(tsx?|css|mjs)$/.test(relative)) continue;
		const head = await readFile(join(targetRoot, relative), "utf8")
			.then((text) => text.slice(0, 200))
			.catch(() => "");
		if (head.includes("Mirrored from axioma/ui/src")) stray.push(relative);
	}
	if (stray.length) {
		if (check)
			throw new Error(
				`generated file not in the ${app} manifest: ${stray.join(", ")}`,
			);
		for (const relative of stray) {
			await rm(join(targetRoot, relative));
			console.log(`ui pruned ${app}/${relative}`);
		}
	}

	for (const relative of entries) covered.add(relative);
	console.log(`ui ${check ? "verified" : "->"} ${app}`);
}

for (const relative of sourceFiles) {
	if (!covered.has(relative))
		throw new Error(`source file not mirrored anywhere: ${relative}`);
}

console.log(
	check
		? "\nui copies are fresh."
		: "\ndone. Both apps receive the governed UI from the manifest.",
);
