export const deviceCopy = {
	connectComputer: "Connect a computer",
	pageTitle: "Connect a computer · Axiōma",
	pageDescription:
		"Link this computer to your account so it can be selected when you ask for help.",
	connectDescription:
		"Enter the code shown by axel-cli on the computer you want to connect.",
	codeLabel: "Code shown by axel-cli",
	codePlaceholder: "ABCDEF-1234",
	codeError: "Enter the code shown on your computer.",
	connecting: "Connecting…",
	connectError: "We couldn’t use that code. Check it and try again.",
	connected: "Computer connected.",
	claimHeading: "Enter your code",
	heading: "Your computers",
	online: "Online",
	offline: "Offline",
	lastSeen: "Last seen",
	loading: "Loading your computers…",
	error: "We couldn’t load your computers.",
	empty: "No computers connected yet.",
	tryAgain: "Try again",
	disconnect: "Disconnect",
	disconnectTitle: "Disconnect this computer?",
	disconnectBody:
		"It will stop appearing when you ask for help, and no one will be able to act on it for you. You can connect it again with a new code from axel-cli.",
	disconnectCancel: "Keep it connected",
	disconnecting: "Disconnecting…",
	disconnectError: "We couldn’t disconnect that computer. Try again.",
	disconnected: "Computer disconnected.",
} as const;
