import { assetsContract } from "./assets";
import { automationContract } from "./automation";
import { catalogueContract } from "./catalogue";
import { changesContract } from "./changes";
import { cmdbContract } from "./cmdb";
import { connectorContract } from "./connectors";
import { deviceProposalsContract } from "./device-proposals";
import { devicesContract } from "./devices";
import { documentsContract } from "./documents";
import { environmentsContract } from "./environments";
import { healthContract } from "./health";
import { identityContract } from "./identity";
import { intakeContract } from "./intake";
import { knowledgeContract } from "./knowledge";
import { mailContract } from "./mail";
import { problemsContract } from "./problems";
import { schedulingContract } from "./scheduling";
import { statusContract } from "./status";
import { suppliersContract } from "./suppliers";
import { reporterUpdateTicket, ticketsContract } from "./tickets";

export const appContract = {
	listForms: catalogueContract.listForms,
	createForm: catalogueContract.createForm,
	updateForm: catalogueContract.updateForm,
	publishForm: catalogueContract.publishForm,
	setSubcategoryForm: catalogueContract.setSubcategoryForm,
	listCatalogue: catalogueContract.listCatalogue,
	listProblems: problemsContract.listProblems,
	getProblem: problemsContract.getProblem,
	createProblem: problemsContract.createProblem,
	updateProblem: problemsContract.updateProblem,
	linkProblemTickets: problemsContract.linkProblemTickets,
	closeProblem: problemsContract.closeProblem,
	getTicketServiceRecords: ticketsContract.getTicketServiceRecords,
	listChanges: changesContract.listChanges,
	getChange: changesContract.getChange,
	createChange: changesContract.createChange,
	updateChange: changesContract.updateChange,
	voteOnChange: changesContract.voteOnChange,
	listKnowledgeArticles: knowledgeContract.listKnowledgeArticles,
	getKnowledgeArticle: knowledgeContract.getKnowledgeArticle,
	createKnowledgeArticle: knowledgeContract.createKnowledgeArticle,
	updateKnowledgeArticle: knowledgeContract.updateKnowledgeArticle,
	listPublicKnowledge: knowledgeContract.listPublicKnowledge,
	getPublicKnowledgeArticle: knowledgeContract.getPublicKnowledgeArticle,
	listRequestCatalogue: catalogueContract.listRequestCatalogue,
	createCatalogueRequest: catalogueContract.createCatalogueRequest,
	listDeviceProposals: deviceProposalsContract.listDeviceProposals,
	decideDeviceProposal: deviceProposalsContract.decideDeviceProposal,
	listApprovals: catalogueContract.listApprovals,
	decideApproval: catalogueContract.decideApproval,
	getMyApprovalStatus: catalogueContract.getMyApprovalStatus,
	listCmdbClasses: cmdbContract.listCmdbClasses,
	createCmdbClass: cmdbContract.createCmdbClass,
	updateCmdbClass: cmdbContract.updateCmdbClass,
	deleteCmdbClass: cmdbContract.deleteCmdbClass,
	listCmdbObjects: cmdbContract.listCmdbObjects,
	getCmdbObject: cmdbContract.getCmdbObject,
	cmdbImpact: cmdbContract.cmdbImpact,
	listTicketCmdbObjects: cmdbContract.listTicketCmdbObjects,
	linkTicketCmdbObject: cmdbContract.linkTicketCmdbObject,
	unlinkTicketCmdbObject: cmdbContract.unlinkTicketCmdbObject,
	listCmdbRelationshipTypes: cmdbContract.listCmdbRelationshipTypes,
	createCmdbRelationshipType: cmdbContract.createCmdbRelationshipType,
	createCmdbObjectRelationship: cmdbContract.createCmdbObjectRelationship,
	listFieldDefinitions: automationContract.listFieldDefinitions,
	listTicketFieldDefinitions: automationContract.listTicketFieldDefinitions,
	createFieldDefinition: automationContract.createFieldDefinition,
	setFieldDefinitionActive: automationContract.setFieldDefinitionActive,
	listTicketRules: automationContract.listTicketRules,
	createTicketRule: automationContract.createTicketRule,
	updateTicketRule: automationContract.updateTicketRule,
	deleteTicketRule: automationContract.deleteTicketRule,
	listWorkflows: automationContract.listWorkflows,
	createWorkflow: automationContract.createWorkflow,
	updateWorkflow: automationContract.updateWorkflow,
	deleteWorkflow: automationContract.deleteWorkflow,
	listWebhookDeliveries: automationContract.listWebhookDeliveries,
	retryWebhookDeliveries: automationContract.retryWebhookDeliveries,
	listNotifications: automationContract.listNotifications,
	markNotificationRead: automationContract.markNotificationRead,
	listSavedViews: automationContract.listSavedViews,
	createSavedView: automationContract.createSavedView,
	updateSavedView: automationContract.updateSavedView,
	deleteSavedView: automationContract.deleteSavedView,
	reconcileSearch: automationContract.reconcileSearch,
	listApiKeys: automationContract.listApiKeys,
	createApiKey: automationContract.createApiKey,
	updateApiKey: automationContract.updateApiKey,
	revokeApiKey: automationContract.revokeApiKey,
	search: automationContract.search,
	readStatus: statusContract.readStatus,
	upsertStatusService: statusContract.upsertStatusService,
	upsertImpactLevel: statusContract.upsertImpactLevel,
	createStatusIncident: statusContract.createStatusIncident,
	updateStatusIncident: statusContract.updateStatusIncident,
	readDeviceInventory: assetsContract.readDeviceInventory,
	listAssets: assetsContract.listAssets,
	previewAssetImport: assetsContract.previewAssetImport,
	importAssets: assetsContract.importAssets,
	listAssetImportRuns: assetsContract.listAssetImportRuns,
	listAssetImportRejections: assetsContract.listAssetImportRejections,
	listAssetHistory: assetsContract.listAssetHistory,
	setAssetDynamicFields: assetsContract.setAssetDynamicFields,
	listTicketOrigins: mailContract.listTicketOrigins,
	listMailboxes: mailContract.listMailboxes,
	upsertMailbox: mailContract.upsertMailbox,
	deleteMailbox: mailContract.deleteMailbox,
	listMailboxActivity: mailContract.listMailboxActivity,
	ingestChannelMessage: mailContract.ingestChannelMessage,
	checkoutAsset: assetsContract.checkoutAsset,
	checkinAsset: assetsContract.checkinAsset,
	listSoftwareEntitlements: assetsContract.listSoftwareEntitlements,
	createSoftwareEntitlement: assetsContract.createSoftwareEntitlement,
	allocateSoftwareLicence: assetsContract.allocateSoftwareLicence,
	revokeSoftwareAllocation: assetsContract.revokeSoftwareAllocation,
	readSoftwareCompliance: assetsContract.readSoftwareCompliance,
	setTicketSchedule: schedulingContract.setTicketSchedule,
	snoozeTicket: schedulingContract.snoozeTicket,
	listCalendar: schedulingContract.listCalendar,
	listRecurrences: schedulingContract.listRecurrences,
	createRecurrence: schedulingContract.createRecurrence,
	updateRecurrence: schedulingContract.updateRecurrence,
	deleteRecurrence: schedulingContract.deleteRecurrence,
	triggerRecurrences: schedulingContract.triggerRecurrences,
	getDashboardArrangement: automationContract.getDashboardArrangement,
	setDashboardArrangement: automationContract.setDashboardArrangement,
	listAuthProviders: identityContract.listAuthProviders,
	listEmailTemplates: mailContract.listEmailTemplates,
	createEmailTemplate: mailContract.createEmailTemplate,
	updateEmailTemplate: mailContract.updateEmailTemplate,
	deleteEmailTemplate: mailContract.deleteEmailTemplate,
	listEmailTemplateRules: mailContract.listEmailTemplateRules,
	setEmailTemplateRule: mailContract.setEmailTemplateRule,
	deleteEmailTemplateRule: mailContract.deleteEmailTemplateRule,
	previewDirectorySync: identityContract.previewDirectorySync,
	applyDirectorySync: identityContract.applyDirectorySync,
	listDocuments: documentsContract.listDocuments,
	createLinkDocument: documentsContract.createLinkDocument,
	unlinkDocument: documentsContract.unlinkDocument,
	startIntakeDraft: intakeContract.startIntakeDraft,
	sendIntakeMessage: intakeContract.sendIntakeMessage,
	getIntakeDraft: intakeContract.getIntakeDraft,
	patchIntakeDraft: intakeContract.patchIntakeDraft,
	submitIntakeDraft: intakeContract.submitIntakeDraft,
	discardIntakeDraft: intakeContract.discardIntakeDraft,
	intakeCapabilities: intakeContract.intakeCapabilities,
	listSuppliers: suppliersContract.listSuppliers,
	listContracts: suppliersContract.listContracts,
	listEnvironments: environmentsContract.listEnvironments,
	createEnvironment: environmentsContract.createEnvironment,
	updateEnvironment: environmentsContract.updateEnvironment,
	deleteEnvironment: environmentsContract.deleteEnvironment,
	linkTicketEnvironment: environmentsContract.linkTicketEnvironment,
	unlinkTicketEnvironment: environmentsContract.unlinkTicketEnvironment,
	listEmailSendLog: mailContract.listEmailSendLog,
	healthCheck: healthContract.healthCheck,
	privateData: identityContract.privateData,
	createTicket: ticketsContract.createTicket,
	listTickets: ticketsContract.listTickets,
	getMyTicket: ticketsContract.getMyTicket,
	heartbeatTicketPresence: ticketsContract.heartbeatTicketPresence,
	listTicketPresence: ticketsContract.listTicketPresence,
	listTicketSla: ticketsContract.listTicketSla,
	submitTicketCsat: ticketsContract.submitTicketCsat,
	getTicket: ticketsContract.getTicket,
	addTicketMessage: ticketsContract.addTicketMessage,
	addMyTicketMessage: ticketsContract.addMyTicketMessage,
	getRun: ticketsContract.getRun,
	startRun: ticketsContract.startRun,
	cancelRun: ticketsContract.cancelRun,
	listTicketLinks: ticketsContract.listTicketLinks,
	linkTickets: ticketsContract.linkTickets,
	unlinkTickets: ticketsContract.unlinkTickets,
	mergeTickets: ticketsContract.mergeTickets,
	unmergeTicket: ticketsContract.unmergeTicket,
	listTicketAudit: ticketsContract.listTicketAudit,
	listTicketRuleFirings: ticketsContract.listTicketRuleFirings,
	listTicketTimeEntries: ticketsContract.listTicketTimeEntries,
	addTicketTimeEntry: ticketsContract.addTicketTimeEntry,
	lookupTicket: ticketsContract.lookupTicket,
	listTicketAssignmentOptions: ticketsContract.listTicketAssignmentOptions,
	listPendingReasons: ticketsContract.listPendingReasons,
	setTicketDynamicFields: ticketsContract.setTicketDynamicFields,
	updateTicket: ticketsContract.updateTicket,
	listMyDevices: devicesContract.listMyDevices,
	claimDevice: devicesContract.claimDevice,
	releaseMyDevice: devicesContract.releaseMyDevice,
	createDeviceEnrolmentToken: devicesContract.createDeviceEnrolmentToken,
	rotateDeviceCredential: devicesContract.rotateDeviceCredential,
	revokeDevice: devicesContract.revokeDevice,
	listDevices: devicesContract.listDevices,
	listDeviceCommands: devicesContract.listDeviceCommands,
	ticketStats: ticketsContract.ticketStats,
	listCapabilities: identityContract.listCapabilities,
	listPeople: identityContract.listPeople,
	setUserKind: identityContract.setUserKind,
	listRoles: identityContract.listRoles,
	getRole: identityContract.getRole,
	updateRoleCapabilities: identityContract.updateRoleCapabilities,
	assignRole: identityContract.assignRole,
	listDepartments: identityContract.listDepartments,
	createDepartment: identityContract.createDepartment,
	listTeams: identityContract.listTeams,
	createTeam: identityContract.createTeam,
	updateTeam: identityContract.updateTeam,

	// ITSM connector administration.
	portalIsFrontDoor: connectorContract.portalIsFrontDoor,
	getTicketConnectorOrigin: connectorContract.getTicketConnectorOrigin,
	getTicketProposal: connectorContract.getTicketProposal,
	markProposalOpened: connectorContract.markProposalOpened,
	recordProposalVerdict: connectorContract.recordProposalVerdict,
	connectorAgreement: connectorContract.connectorAgreement,
	listConnectors: connectorContract.listConnectors,
	createConnector: connectorContract.createConnector,
	updateConnector: connectorContract.updateConnector,
	deleteConnector: connectorContract.deleteConnector,
	testConnector: connectorContract.testConnector,
	previewConnectorSync: connectorContract.previewConnectorSync,
	triggerConnectorSync: connectorContract.triggerConnectorSync,
	listConnectorRuns: connectorContract.listConnectorRuns,
	listConnectorWritebacks: connectorContract.listConnectorWritebacks,
	retryConnectorWriteback: connectorContract.retryConnectorWriteback,
	listDispatchLedger: connectorContract.listDispatchLedger,
	listFieldMappings: connectorContract.listFieldMappings,
	upsertFieldMapping: connectorContract.upsertFieldMapping,
	deleteFieldMapping: connectorContract.deleteFieldMapping,
	listEnvironmentRoutes: connectorContract.listEnvironmentRoutes,
	upsertEnvironmentRoute: connectorContract.upsertEnvironmentRoute,
	deleteEnvironmentRoute: connectorContract.deleteEnvironmentRoute,
};

export type AppContract = typeof appContract;

export const portalContract = {
	listNotifications: automationContract.listNotifications,
	markNotificationRead: automationContract.markNotificationRead,
	listTicketFieldDefinitions: automationContract.listTicketFieldDefinitions,
	readStatus: statusContract.readStatus,
	listAuthProviders: identityContract.listAuthProviders,
	privateData: identityContract.privateData,
	listPublicKnowledge: knowledgeContract.listPublicKnowledge,
	getPublicKnowledgeArticle: knowledgeContract.getPublicKnowledgeArticle,
	listRequestCatalogue: catalogueContract.listRequestCatalogue,
	createCatalogueRequest: catalogueContract.createCatalogueRequest,
	getMyApprovalStatus: catalogueContract.getMyApprovalStatus,
	listDocuments: documentsContract.listDocuments,
	createLinkDocument: documentsContract.createLinkDocument,
	// The employee has to be able to take a screenshot back off their own draft.
	// Without this the tray could only forget an attachment locally, and
	// `submitIntake` re-parented the link onto the ticket regardless.
	// Authorisation is unchanged: the handler still resolves the target's owner.
	unlinkDocument: documentsContract.unlinkDocument,
	startIntakeDraft: intakeContract.startIntakeDraft,
	sendIntakeMessage: intakeContract.sendIntakeMessage,
	getIntakeDraft: intakeContract.getIntakeDraft,
	patchIntakeDraft: intakeContract.patchIntakeDraft,
	submitIntakeDraft: intakeContract.submitIntakeDraft,
	discardIntakeDraft: intakeContract.discardIntakeDraft,
	intakeCapabilities: intakeContract.intakeCapabilities,
	createTicket: ticketsContract.createTicket,
	listTickets: ticketsContract.listTickets,
	getMyTicket: ticketsContract.getMyTicket,
	submitTicketCsat: ticketsContract.submitTicketCsat,
	addMyTicketMessage: ticketsContract.addMyTicketMessage,
	updateTicket: reporterUpdateTicket,
	listMyDevices: devicesContract.listMyDevices,
	claimDevice: devicesContract.claimDevice,
	releaseMyDevice: devicesContract.releaseMyDevice,
	portalIsFrontDoor: connectorContract.portalIsFrontDoor,
};

export type PortalContract = typeof portalContract;
